traffic_ops/app/db/admin.pl
I think this line is obsolete, and should be removed?
=> Remove obsolete remnant of previous versions(?)

traffic_ops/app/db/admin.pl
Reverts Comcast/traffic_control#51
- CLA not signed.
=> Revert "Remove obsolete remnant of previous versions(?)"

docs/source/admin/traffic_ops_using.rst
=> This closes #58 - forgot a dot

traffic_server/README.md, traffic_server/patches/trafficserver-5.2.0-791ddc4.patch, traffic_server/plugins/astats_over_http/Makefile.am, traffic_server/plugins/astats_over_http/README.md, traffic_server/plugins/astats_over_http/astats.config.example, traffic_server/plugins/astats_over_http/astats_over_http.c, traffic_server/plugins/astats_over_http/astats_over_http.spec, traffic_server/spec/trafficserver.spec
This adds a patch and spec file for traffic server and also the astats_over_http plugin needed to properly run traffic_control.
=> Add traffic_server support directory.

traffic_ops/app/lib/UI/Utils.pm
Updated for the release 1.1.1 hotfix to fix carton
=> updated for release 1.1.1

traffic_ops/app/bin/tests/run_integration_tests.sh, traffic_ops/app/bin/tests/run_unit_tests.sh
Changed path to /opt/traffic_ops/app/local/bin/prove for CI
=> adjusted test scripts path to real location

traffic_ops/app/lib/MojoPlugins/Job.pm, traffic_ops/app/lib/UI/Job.pm, traffic_ops/app/lib/UI/Server.pm, traffic_ops/app/t/api/1.1/job.t
This patch prevents offline servers getting an ort update pending flag
=> Purge patch

traffic_ops/app/lib/UI/Utils.pm
=> updated for 1.1.2

traffic_ops/app/lib/UI/ConfigFiles.pm
Change cacheurl_remap.config to cacheurl_qstring.config, and add line to remap.config on mids.
=> Adding remap.config support for cacheurl query string dropping at mids

traffic_ops/app/lib/MojoPlugins/DnssecKeys.pm, traffic_ops/app/lib/MojoPlugins/SslKeys.pm, traffic_ops/client/server.go
=> change default key encryption to 2048

traffic_ops/bin/traffic_ops_ort.pl, traffic_ops/rpm/traffic_ops_ort.spec
=> Add cacheurl_qstring.config to traffic_line -x'able config files.

traffic_ops/app/lib/MojoPlugins/Metrics.pm
its better to leave it and null pad it...
related to https://github.com/Comcast/traffic_control/issues/84
=> no need to remove empty data series

traffic_ops/app/lib/TrafficOps.pm, traffic_ops/app/lib/UI/ConfigFiles.pm
Fix edit profile route and add port override for parent.config
=> Fix edit profile router. Closes #164

traffic_ops/app/lib/Utils/Helper/Datasource.pm
the remove_empty_series method was taken out of commission in https://github.com/Comcast/traffic_control/commit/8da6a963e8827ac94667f1039e9ed476e3ad7118
=> Cleans up dead code - remove_empty_series

traffic_ops/app/lib/API/Cdn.pm, traffic_ops/app/t/api/1.1/cdn.t
=> fixed cdn/dnssec tests

traffic_ops/app/lib/API/DeliveryService.pm
https://github.com/Comcast/traffic_control/issues/206
=> fixes issues 206

traffic_ops/app/lib/MojoPlugins/SslKeys.pm
=> proper deref on line 165. this closes #211.

traffic_ops/app/lib/API/DeliveryService/SslKeys.pm, traffic_ops/bin/traffic_ops_ort.pl, traffic_ops/rpm/traffic_ops_ort.spec
=> Ssl updates

traffic_ops/app/lib/UI/Job.pm
=> ternary operator wasn't working correctly so used if/else instead.  

traffic_ops/bin/traffic_ops_ort.pl, traffic_ops/rpm/traffic_ops_ort.spec
Didn't do branch...does that break things?
=> ORT updates

traffic_ops/app/lib/MojoPlugins/DnssecKeys.pm, traffic_ops/app/lib/UI/SslKeys.pm, traffic_ops/app/templates/delivery_service/edit.html.ep, traffic_ops/app/templates/ssl_keys/add.html.ep
=> fixed issues with ssl certs UI

misc/changelog.pl
Run it with `changelog.pl <owner> <repo> <milestone>`
Example: `changelog.pl Comcast traffic_control 1.1.3`
=> Add changelog.pl script to generate a changelog based on github milestones.

traffic_ops/app/lib/API/Cdn.pm, traffic_ops/app/lib/API/DeliveryService.pm, traffic_ops/app/lib/API/Metrics.pm, traffic_ops/app/lib/API/Usage.pm, traffic_ops/app/lib/UI/Redis.pm
Added 'use' stmts for pertinent Delegates.
=> Extensions::Delegate 'use' keywords

traffic_ops/app/cpanfile
=> updated cpanfile to include File::Copy::Recursive

traffic_ops/app/lib/API/DeliveryService.pm, traffic_ops/app/lib/API/Usage.pm, traffic_ops/app/lib/API/v12/DeliveryServiceStats.pm
https://github.com/Comcast/traffic_control/issues/115
=> admin and ops users can skip is_delivery_service assigned check

docs/source/admin/traffic_stats.rst, docs/source/development/traffic_stats.rst, docs/source/overview/traffic_stats.rst
Probably needs a quick glance for spelling and grammar errors...
=> Traffic Stats Documentation

traffic_ops/app/db/migrations/20150721000000_add_stat_date.sql, traffic_ops/app/lib/API/v12/StatsSummary.pm, traffic_ops/app/lib/Schema/Result/StatsSummary.pm, traffic_ops/app/t/api/1.2/stats_summary.t, traffic_ops/client/stats_summary.go, traffic_stats/ts_daily_summary.go
Store the stat date with the daily stats.
Fixed a bug preventing bytes served from getting written.
=> Traffic Stats Changes

traffic_ops/app/db/migrations/20150722100000_add_disname_tr_headers.sql, traffic_ops/app/lib/API/DeliveryService.pm, traffic_ops/app/lib/API/ToExtension.pm, traffic_ops/app/lib/Schema/Result/Deliveryservice.pm, traffic_ops/app/lib/UI/DeliveryService.pm, traffic_ops/app/t/deliveryservice.t, traffic_ops/app/templates/delivery_service/_form.html.ep, traffic_ops/app/templates/delivery_service/add.html.ep
and a small extensions API fix
=> display_name and tr_response_header UI

traffic_ops/client/hardware.go, traffic_ops/client/hardware_test.go, traffic_ops/client/testdata/hardware.json
Just added a hardware file so I could write something for Sean.
=> added a interface to the hardware API to the go client

traffic_ops/install/bin/build_trafficops_perl_library, traffic_ops/install/bin/postinstall, traffic_ops/install/lib/InstallUtils.pm
looks like a lot of changes, but only perltidy run on these 3 files.
=> perltidy on recently updated install files

traffic_ops/app/db/migrations/20150728000000_add_initial_dispersion.sql, traffic_ops/app/lib/API/DeliveryService.pm, traffic_ops/app/lib/API/Topology.pm, traffic_ops/app/lib/Schema/Result/Deliveryservice.pm, traffic_ops/app/lib/UI/Cdn.pm, traffic_ops/app/lib/UI/DeliveryService.pm, traffic_ops/app/lib/UI/Topology.pm, traffic_ops/app/templates/delivery_service/_form.html.ep, traffic_ops/app/templates/delivery_service/add.html.ep, traffic_ops/app/templates/delivery_service/edit.html.ep
perltidy also run on each file modified with this change
=> add initial_dispersion column and UI support for deliveryservice

traffic_ops/app/lib/MojoPlugins/Server.pm
Fixes issue #350 -- add_helper called from MojoPlugins::Server without passing a helper sub
=> remove empty helper

traffic_ops/app/bin/start.pl, traffic_ops/app/lib/TrafficOps.pm
=> relative paths for start.pl, full paths for config dirs

traffic_ops/app/lib/UI/Cdn.pm
crossed paths with another commit that added Dumper call
=> re-add Data::Dumper

traffic_ops/install/data/json/parameter.json
{"name":"astats_over_http","config_file":"package","value":"1.1-2.el6.x86_64"}
{"name":"cacheurl","config_file":"package","value":"1.0-1.el6.x86_64"}
{"name":"dscp_remap","config_file":"package","value":"1.0-1.el6.x86_64"}
{"name":"regex_revalidate","config_file":"package","value":"1.0-1.el6.x86_64"}
{"name":"remap_stats","config_file":"package","value":"1.0-1.el6.x86_64"}
{"name":"url_sign","config_file":"package","value":"1.0-1.el6.x86_64"}
{"name":"trafficserver","config_file":"package","value":"4.0.2-2.el6.x86_64"}
{"name":"trafficserver","config_file":"package","value":"4.2.1-6.el6.x86_64"}
{"name":"url_sig","config_file":"package","value":"1.0-3.el6.x86_64"}
{"name":"astats_over_http","config_file":"package","value":"1.2-3.el6.x86_64"} …
=> Fix #372 - removing all package versions.

traffic_ops/app/lib/MojoPlugins/Stats.pm, traffic_ops/app/lib/TrafficOpsRoutes.pm, traffic_ops/app/lib/UI/Redis.pm, traffic_ops/app/lib/UI/VisualStatus.pm, traffic_ops/app/templates/navbar.html.ep, traffic_ops/app/templates/visual_status/graphs_redis.html.ep
This PR puts the main Redis graph back as **Health->Graph View (old)**, and makes the Influx/Grafana view available as **Health->Graph View (new)**. All the sub links are still going to Grafana/Influx, and the Redis view only supports 24 hours. 
Not sure if this PR will make the transition to Grafana/Influx easier and less risky. 
@dneuman64,  @mtorluemke : your call. Don't merge this PR if you think it'll make things more messy without adding value.
=> this puts the redis main graph back.

traffic_stats/traffic_stats.cfg, traffic_stats/write_traffic_stats.go
=> made retention policy name a configurable value

traffic_ops/app/lib/UI/ConfigFiles.pm
=> Fix parent.config when mulitiple msites are configured.

traffic_ops/app/lib/UI/ConfigFiles.pm
Cherry picked from master
git cherry-pick ca04d3f
git cherry-pick 72780fc
git cherry-pick a184fe7
=> Fix parent selection in multi multi stite config. 

traffic_ops/app/bin/checks/ToFQDNCheck.pl
- This checks DNS to make sure the hostname matches in DNS and the
Traffic Ops DB.
- Checks both IPv4 and IPv6.
=> New FQDN Traffic Ops check

traffic_ops/goto/README.md, traffic_ops/goto/api.go, traffic_ops/goto/index.html, traffic_ops/goto/js/main.js, traffic_ops/goto/outputFormatter/outputFormatter.go, traffic_ops/goto/sqlParser/sqlMapInit.go, traffic_ops/goto/sqlParser/sqlParser.go, traffic_ops/goto/sqlParser/sqlTypeMap.go, traffic_ops/goto/urlParser/urlParser.go
=> Foreign key CRUD implemented

traffic_ops/app/lib/MojoPlugins/Server.pm
=> fixed hardcoded schema file name.  

traffic_ops/app/bin/checks/ToPingCheck.pl, traffic_ops/app/cpanfile
- added some example cron entries
- incremented version
- removed $hostn var
- set syslog to LOG_INFO
- removed $match var
- added $check_lng_name var - configured from $jconf via command line
- added some trim functions
=> add syslog and combined MTU to ToPingCheck.pl

traffic_ops/app/bin/checks/ToRTRCheck.pl
- added example cron entries
- changed the auto flush
- incremented version
- removed $match because it wasn’t being used
- added $chck_lng_nm for syslog messages
- moved $bad_ccr up so that it could be incremented if couldn’t connect
to server
- added some debug code for my benefit.
=> add syslog messages to ToRTRCheck

traffic_ops/app/lib/API/ServerCheck.pm
fix for #457 new OFFLINE server causes .../aadata.json to fail
=> for aadata, skip if no servercheck entry; fix use of array ref; perltidy

traffic_ops/app/lib/API/Cdn.pm
Added back in some code that got removed by a bad commit!
Changed the DNSSEC API to only push keys to Riak if there are actually changes to them.
=> Changes to DNSSEC Key API

traffic_ops/app/lib/UI/Server.pm
Fixes #462, which is root cause of #457.  When a server is updated and type is changed, insert or delete entry in servercheck table accordingly.
=> Addservercheck

traffic_ops/app/db/migrations/20150825175644_shorten_display_name.sql, traffic_ops/app/lib/Schema/Result/Deliveryservice.pm, traffic_ops/app/lib/UI/DeliveryService.pm
Issue #317 : display_name shortened from 1024 to 48
=> TO: deliveryservice/display_name shortened from 1024 to 48

traffic_ops/app/t/deliveryservice.t
for #470 deliveryservice/displayname is now required -- fix unit test to provide it on create
=> fix unit test - display_name now required

traffic_ops/app/lib/TrafficOps.pm
for #415 -- this portion was inadvertently removed
=> re-add inactivity timeout

traffic_ops/install/bin/download_web_deps
0 = default
1 = force IPv4
2 = force IPv6
=> forcing IPv4 web downloads

traffic_ops/app/lib/API/Job.pm, traffic_ops/app/lib/MojoPlugins/Job.pm, traffic_ops/app/t/api/1.1/job.t
For issue #491 -- only admin, operations, or assigned user can submit purge job on a delivery service.
=> add check for user authorized to create purge job

traffic_ops/rpm/build/build_rpm.sh
if either go or ant not available in PATH or go compile fails, exit with a reasonable message and non-zero status
=> check for go and ant in path

traffic_ops/install/go/src/comcast.com/systemtest/systemtest.go
Fixes #519 -- code.google.com is going away, and run go fmt on code
=> remove code.google.com imports

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessEventBuilder.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessRecord.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/NameServer.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/ZoneManager.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/AbstractProtocol.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessEventBuilder.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessRecord.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/TRServlet.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessEventBuilderTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/ZoneManagerTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/ZoneManagerUnitTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/AbstractProtocolTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/TCPTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/UDPTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessEventBuilderTest.java
…tries for client and server error messages instead of putting them in ans field
=> Add result type for DNS access logs, put errors in rerr field instead of conflating ans field

traffic_ops/app/lib/UI/ConfigFiles.pm
#512 -- does substitution of \n for __RETURN__ in cacheurl.   Still requires some testing
=> substitute \n for __RETURN__ in cacheurl

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessEventBuilder.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessRecord.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/ds/DeliveryService.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessEventBuilder.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessRecord.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/StatTracker.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessEventBuilderTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/AbstractProtocolTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessEventBuilderTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/DNSRoutingMissesTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/DeliveryServiceHTTPRoutingMissesTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouterHTTPRoutingMissesTest.java
…  e.g. rtype=MISS.DS_NO_BYPASS
=> Add result type details code as a suffix to the rtype field in access log

traffic_ops/app/lib/UI/ConfigFiles.pm
Traffic Router Additional Headers was already handled.  #512 now complete.
=> __RETURN__ handled in regex_remap

traffic_ops/app/conf/cdn.conf, traffic_ops/app/lib/TrafficOps.pm
new secrets => [ ... ] in cdn.conf.   If missing, fall back to old method.
=> allow secrets to be configurable thru conf file

traffic_ops/app/lib/UI/Profile.pm
=> Join on ID instead of parameter name since that can be duplicated.

traffic_ops/app/lib/UI/Profile.pm
This augments #562 in fixing #131.
=> Missed some variable renames.

traffic_ops/app/lib/API/Cdn.pm, traffic_ops/app/lib/API/DeliveryService.pm, traffic_ops/app/lib/API/Profile.pm, traffic_ops/app/lib/API/Server.pm, traffic_ops/app/lib/TrafficOpsRoutes.pm, traffic_ops/client/cdn.go, traffic_ops/client/server.go
adding route to get cdn by name.
updating client code to use new cdn table.
=> Fix: use CDN Table

traffic_ops/app/conf/cdn.conf, traffic_ops/install/bin/postinstall, traffic_ops/install/lib/InstallUtils.pm, traffic_ops/rpm/README.md, traffic_ops/rpm/build/build_rpm.sh
New prompt during postinstall to add and/or generate a new secret to be added to app/conf/cdn.conf.
Also some cleanup of rpm generation and postinstall scripts to be more robust.
=> postinstall updates secret in cdn.conf

traffic_stats/traffic_stats.go, traffic_stats/traffic_stats.init, traffic_stats/traffic_stats.spec
Make management of this daemon more robust in general
=> More changes for traffic_stats

traffic_ops/app/lib/API/DeliveryService.pm
fixes issue when requesting thru api: /api/1.2/deliveryservices/235/routing.json when delivery service has custom dns or http type, e.g. dns_elsewhere.   Previously would return empty results.  Now returns proper data.
=> API to allow getting stats for custom dns/http type

traffic_ops/install/data/json/parameter.json
=> Postinstall fix to profile parameters

traffic_ops/app/lib/API/Cdn.pm, traffic_ops/app/lib/UI/Topology.pm
traffic ops now returns a deliveryServices->domains section in the CRConfig
=> Added domains array to deliveryServices section of CRConfig

docs/source/development/traffic_stats.rst
changed required versions of GO and InfluxDb, made a small change so building traffic_stats was clear.
=> Update traffic_stats developer doc

traffic_ops/app/lib/API/Federation.pm
returning empty array when no federations found.
ran per tidy.
=> fix: api blows up when no federations found

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessEventBuilder.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/NameServer.java
=> added defensive code to protect against NPEs.  

traffic_ops/app/lib/UI/Server.pm
(cherry picked from commit d62affd678e371f08165ea989a1bed96efcc4438)
=> fixing some typos and added log messages.

traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationRegistryTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationsBuilderTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/CacheRegisterBuilder.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/DnsNameGenerator.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/DnsRoutePerformanceTest.java
no longer need hardcoded hostname
=> Traffic Router DNS perf test now uses data from cr-config

traffic_ops/app/lib/UI/PhysLocation.pm, traffic_ops/app/t/phys_location.t
Fixes #561 .   regex is not adequate for email address validation.
=> use Email::Valid for email address validation

traffic_router/core/src/main/resources/applicationProperties.xml
=> Traffic Router now ignores properties not included in property files

docs/source/overview/traffic_stats.rst
=> fix misspelling

traffic_ops/app/t/api/1.1/riak_adapter.t
=> fix riak adapter test

traffic_ops/app/lib/Extensions/TrafficStats/API/DeliveryServiceStats.pm, traffic_ops/app/lib/Test/TestHelper.pm, traffic_ops/app/t/api/1.2/deliveryservice_stats.t
=> fixes deliveryservice_stats.json crash when user does not have ds

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/cache/CacheRegister.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/ds/DeliveryServiceMatcher.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/request/RequestMatcher.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/ComparableStringByLength.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/cache/CacheRegisterTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/ds/DeliveryServiceMatcherTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/request/RequestMatcherTest.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/CacheRegisterBuilder.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/util/ComparableStringByLengthTest.java
Use the regex from the configuration to order matchers
=> TrafficRouter now attempts to select the most specific delivery service

traffic_ops/app/lib/UI/Topology.pm
=> check for undefs when building profile cache list

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/CidrAddress.java
=> Trim CZMap entries so that TR can load the CZ file.

build/functions.sh, traffic_ops/build/traffic_ops.spec
=> fix exec permissions in rpm; add check for rpmbuild

traffic_ops/install/bin/web_deps.txt
(cherry picked from commit 78451e45967cbfe08c8087f01f530c5e49b0be95)
=> remove jmenu entries -- were removed from original source repo

traffic_ops/app/lib/API/Federation.pm, traffic_ops/app/t/api/1.2/federation_internal.t
=> Adding cdnName param to /internal/api/federations.json

docs/source/admin/traffic_ops_install.rst, traffic_ops/app/conf/production/database.conf, traffic_ops/install/bin/postinstall, traffic_ops/install/data/json/parameter.json, traffic_ops/install/go/src/comcast.com/dataload/dataload.go
updaing postinstall to install all of the parameters in parameter.json.
updating production db config to reflect correct prod db info
=> fixing postinstall

traffic_ops/app/lib/UI/Profile.pm
Fixes #862 
Only happens when the first param to be checked does not exist in db,  and just produces a warning in the log,  so minor impact,  but change is also minor.
Also perltidy'd..
=> check if param done only after checking that it exists

traffic_ops/app/lib/MojoPlugins/DnssecKeys.pm
=> Fixed generate_store_dnssec_keys to only generate keys for HTTP and DNS deliveryservices. 

traffic_ops/app/lib/API/Job.pm, traffic_ops/app/t/api/1.1/job.t
Forced the dsId to be a required field for API Purge requests Fixes: 878
=> forced the dsId to be a required field in all cases

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessEventBuilder.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/TRServlet.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessEventBuilderTest.java
=> Traffic Router now logs value from x-mm-client-ip http header or fakeClientIpAddress query parameter as 'chi' value, closes #882

traffic_ops/app/lib/MojoPlugins/Server.pm
gathers available servers of the given type.  Selects one at random, avoiding most recently used of that type unless it's the only one available.  Currently used only for influxdb and riak servers.
=> make available server selection more robust

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/TRServlet.java
=> Traffic Router - I missed removing the superfluous logger

traffic_ops/app/lib/UI/DeliveryService.pm
=> fixed create_dnssec_keys method to correctly populate TTL when keys are created for a new deliveryservice.

traffic_ops/install/lib/WebDep.pm
Fixes #893 -- mkpath before checking for abs path
=> mkpath on final_dir when does not exist before trying to get absolute path

traffic_ops/app/lib/API/Cdn.pm, traffic_ops/app/lib/MojoPlugins/DnssecKeys.pm, traffic_ops/app/lib/UI/DeliveryService.pm, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSKeyPairWrapper.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/SignatureManager.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/ZoneManager.java
Please see the individual commits for specifics.
=> Traffic Router and Ops backports from master for 1.3.0 RC4 for DNSSEC related bug fixes.

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationMapping.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationRegistry.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/NetworkNode.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/CidrAddress.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/NetworkNodeUnitTest.java
=> Fix overlapping subnets

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouterTest.java
=> Record geolocation in Traffic Router results for results from geolocation services

traffic_ops/app/lib/UI/ConfigFiles.pm
skip row if job_deliveryservice is null
=> fixes crash during genfiles

traffic_monitor/src/main/conf/log4j.properties, traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/Event.java
=> fixes #900

traffic_monitor/pom.xml, traffic_monitor/src/main/scripts/postremove.sh
=> Add post uninstall step that removes old exploded ROOT.war directory

traffic_ops/app/lib/API/DeliveryService.pm, traffic_ops/app/lib/API/Server.pm, traffic_ops/app/lib/MojoPlugins/DeliveryService.pm, traffic_ops/app/lib/UI/Utils.pm
=> Allowing ldap users to view Delivery Services and Servers.

traffic_ops/app/lib/UI/Topology.pm
(cherry picked from commit 1f24fc8e0e747027d936953a68b1032435d30a9b)
Fixes #944 for 1.3.x
=> use ref for hash value

traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/DsState.java, traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/DsWatcher.java
=> Fix github issue #669

traffic_ops/app/templates/visual_status/graphs.html.ep
This fixes #1000
(cherry picked from commit 1cd3e4c1420e2c6d4fa4adbfb9afb50798df8143)
=> fixed issue with stats not refreshing. 

traffic_stats/influxdb_tools/README.txt, traffic_stats/traffic_stats.cfg, traffic_stats/traffic_stats.go
=> Put chunking back in to address OOM issues

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/TRServlet.java
=> check ds available, as requested ds may not exist

traffic_ops/app/lib/MojoPlugins/Server.pm
also add server name to an error
=> Change server connection logging to debug.

traffic_ops/install/data/profiles/profile.traffic_monitor.traffic_ops
=> Fix Traffic Ops install profile param

traffic_stats/build/traffic_stats.spec, traffic_stats/influxdb_tools/README.txt, traffic_stats/influxdb_tools/create_ts_databases.go, traffic_stats/influxdb_tools/sync_ts_databases.go, traffic_stats/traffic_stats.go
(cherry picked from commit 4691f9f67adafe62605c1b87614ccd00c7f9286f)
=> changes due to influxdb moving their github repo

traffic_ops/app/lib/UI/DeliveryService.pm
fixes #1074.   References to ds.type and ds.type.id were inconsistent.  Introduced helper fcns to make more robust
=> fix reference to type/type.id parameter for ds/update

traffic_ops/app/lib/UI/DeliveryService.pm
(cherry picked from commit 8fbce5d678b20b18d9b01d4ce292cb8baea1d305)
fixes #1074
=> fix deliveryservice type references

traffic_ops/app/lib/MojoPlugins/DeliveryService.pm
(cherry picked from commit 9d2123549d2165fb78b1448d344f013223169323)
=> if param is blank, accept default passed instead

traffic_ops/app/lib/UI/ConfigFiles.pm
This is moderately dangerous and should be thoroughly tested.
ATS documentation and code suggests volumes should sum to 100%,
and nothing suggests the current 1% setting is the designed
usage. But, changing how ATS perceives volumes is a bit uncertain.
This changes volumes to equally sum to 100%. E.g., two volumes are set
to 50% each. Three volumes are 33% each.
Also:
- Make Traffic Ops volume.config generation add SSD volume, if
`SSD_Volume`, `SSD_Drive_Prefix`, and `SSD_Drive_Letters` exist.
- Make Traffic Ops storage.config add SSD volume path and number.
Resolves #1078
=> Change Traffic Ops volume.config to sum to 100%

traffic_ops/app/lib/UI/DeliveryService.pm
in c2f9ac5731a2e18f4a6a4c87e1e4768da279c18d
=> remove regional_geo_blocking reference -- snuck in due to merge conflict

traffic_ops/experimental/server/db/schema.sql
This is a WIP. Will want to still redo other things like type table. So don't get too hung up on things not yet done.
=> Switch to natural keys and better data types.

traffic_ops/app/lib/UI/ConfigFiles.pm
(cherry picked from commit 0f8b70600b3aad9711056ff777cd24b05b46c5e9)
=> parent.config -- skip line if no remap origin

traffic_ops/app/lib/API/Federation.pm, traffic_ops/app/t/api/1.2/federation_external.t
fixes #818 
@elsloo, @dneuman64 please check this to see if it resolves the issue..
=> use range2cidr instead of cidrvalidate

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/ZoneManager.java
ZoneManagerTest is assuming it is present.
=> Traffic Router, ZoneManager now creates auto zones directory if needed

traffic_ops/experimental/server/api/api.go
Not sure why that was missing?
=> add deliveryservice/{id} route

traffic_ops/app/db/admin.pl
This fixes postinstall not working if the MySQL database is on a different server.
=> Fix TO admin.pl to use MySQL host and port params

docker/Traffic_Ops_Dockerfile, docker/Traffic_Ops_Dockerfile_run.sh
This removes Traffic_Ops_Dockerfile manual fixes of Traffic Ops bugs which
have since been fixed in 1.4.
=> Remove TO Dockerfile manual fixes

traffic_stats/traffic_stats.go
=> fix issue with daily_maxgbps being written as daily_bytesserved

traffic_ops/app/lib/MojoPlugins/Response.pm, traffic_ops/app/lib/UI/ConfigFiles.pm
In ConfigFiles.pm, if the response coming back from method called by dispatch table starts with Error, send a 500 response
This closes #1168
=> Return a 500 response if an Error is encountered in ConfigFiles.pm

traffic_router/api/pom.xml, traffic_router/api/src/main/java/com/comcast/cdn/traffic_control/traffic_router/api/util/TrafficRouterImporter.java, traffic_router/build/pom.xml, traffic_router/core/pom.xml, traffic_router/core/src/main/webapp/WEB-INF/applicationContext.xml, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/TestBase.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/TrafficRouterStart.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandlerTest.java, traffic_router/testServer/src/main/java/com/comcast/cdn/traffic_control/traffic_router/TestServer.java
=> Traffic Router - fix ObjectMapper dependency that was causing API to 500

traffic_ops/app/lib/TrafficOps.pm, traffic_ops/app/lib/UI/ConfigFiles.pm
(cherry picked from commit 72703d07d027bd6d8f04826bbf8c5b57904c67f7)
=> Added time to serve and user agent to the Traffic Ops access log and improved performance of generation of ip_allow.config

traffic_ops/install/bin/postinstall
=> Fix postinstall prompting for TO user every time

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/ZoneManager.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/AbstractServiceUpdater.java
Stops the service updater thread started by the RegionalGeoUpdater when the URL parameter is not configured.
=> Stop service updater thread started by RegionalGeoUpdater

traffic_ops/app/lib/UI/ConfigFiles.pm
(cherry picked from commit ec95220abafaa76c2a97a78a80c21724b63140a1)
=> fix #1191 right this time. Sorry.

traffic_ops/experimental/ui/app/src/common/modules/form/cacheGroup/edit/FormEditCacheGroupController.js, traffic_ops/experimental/ui/app/src/common/modules/form/cacheGroup/form.cacheGroup.tpl.html, traffic_ops/experimental/ui/app/src/common/modules/form/deliveryService/FormDeliveryServiceController.js, traffic_ops/experimental/ui/app/src/common/modules/form/deliveryService/form.deliveryService.tpl.html
=> TO 2.0 UI - incremental PR

traffic_ops/experimental/ui/README.md
install requires ruby / compass
=> TO 2.0 UI - install requires ruby / compass

traffic_ops/app/lib/UI/Server.pm
=> always update IPv6 address and gateway

traffic_ops/bin/traffic_ops_ort.pl
Fixes #1050. The split should only be done when defined.
=> ORT: Remove initialized value complaints on plugin_config_file

CONTRIBUTORS.md
contributed new REST API endpoints for TO
=> Added York Ma

CONTRIBUTORS.md
just checked out in github and realized line-ending ** was missing...
=> fix line-ending in CON

traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/CacheDetailsPage.java, traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/DsDetailsPage.java, traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/StateDetailsPage.java
=> Traffic Monitor, fix page not found issue #1249

traffic_ops/app/lib/UI/DeliveryServiceServer.pm
=> Fix TO Clone DS Assignments to exclude other CDNs

traffic_stats/traffic_stats.go
Also changed the code to use the ping() method (thanks @PSUdaemon) instead of querying the database when creating a client.
=> Fixed an issue where data was getting written to DS stats with cachegroup = 'EDGE'

traffic_ops/experimental/server/auth/auth.go
=> Fix TO 2.0 to return 401 for login failures

traffic_ops/experimental/server/db/schema.sql
This adds safety, by making it impossible to e.g. set a `server` type to `AAAA`, and further by adding foreign key constraints so e.g. a `server` type _must_ be an entry in the `server_types` table.
This also retains the flexibility of being able to add types as data at runtime and in production.
We should consider changing types to be constraints, e.g. `CREATE TABLE staticdnsentry (type text CHECK (type in ('A', 'AAAA', 'CNAME')),`. Constraints would simplify the schema and reduce the number of tables, and add further safety, arguably with a flexibility tradeoff. But that's a bigger discussion.
=> Add TO2.0 DB tables for each type of type

traffic_ops/app/lib/UI/ConfigFiles.pm
=> uniquify parent info for parent.config

traffic_ops/app/lib/TrafficOps.pm
This hopefully fixes some issues we have been seeing with Riak
=> set default ssl session cache

traffic_ops/app/lib/Connection/RiakAdapter.pm, traffic_ops/app/lib/TrafficOps.pm
This is a POC that I am handing off to @dangogh.
=> POC: Add connection caching to TO

traffic_ops/app/lib/UI/SslKeys.pm
added in better error handling when SSL keys aren't succesfully created.  
Fixed an issue with keys for http/https DSs not getting created successfully.
This closes #1268
=> Traffic Ops now can generate/re-generate keys for http/https DSs

traffic_ops/app/lib/UI/SslKeys.pm
added in better error handling when SSL keys aren't succesfully created.  
Fixed an issue with keys for http/https DSs not getting created successfully.
This closes #1268 
(cherry picked from commit ce04b7a718c37e1d363543f8559d1d9a1b6061a1)
=> BACKPORT: Traffic Ops now can generate/re-generate keys for http/https DSs 

traffic_stats/traffic_stats.go
integrating changes from TO Client code changes.  Adding log message if traffic monitors are set to anything but online.
Fixes: #1327
=> update TS to work with TO Client changes

traffic_ops/bin/traffic_ops_ort.pl
This disperses ORT runs out over a default 5 minute interval and also adds exponential back off to retries.
=> Spread out the ORT run better

traffic_ops/app/db/migrations/20160329141600_add_ds_protocol_not_null.sql
=> Change TO ds table protocol column to not null

traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/CacheWatcher.java
fixes #1316
(cherry picked from commit 8ef5e882210ba356328e114b4713f224e109afab)
=> Traffic Monitor always clears list of updaters after fetching all stats

traffic_router/build/pom.xml
(cherry picked from commit 868511d64cfe968acc0ad340014271e80f56a07e)
=> Specified the correct version dependency for the jdk package.

traffic_ops/install/data/profiles/profile.global.traffic_ops, traffic_ops/install/data/profiles/profile.trafficserver_edge.traffic_ops, traffic_ops/install/data/profiles/profile.trafficserver_mid.traffic_ops
I'll cherry-pick to `1.5.x` as soon as it's merged.
=> Update TO default profiles for 1.5

traffic_ops/app/bin/checks/ToRTRCheck.pl
* incremented version
* made some debug messages more clear
* moved cdnName retrieval from profiles to server info
=> Minor updates to ToRTRCheck for 1.3.0 compatibility

traffic_router/core/src/main/webapp/WEB-INF/applicationContext.xml, traffic_router/core/src/main/webapp/WEB-INF/status-servlet.xml, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/configuration/NeustarConfiguration.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/configuration/TrafficRouterConfigurationListener.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/data/NeustarDatabaseUpdater.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/data/TarExtractor.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/files/FilesMover.java, traffic_router/neustar/src/test/java/configuration/PeriodicUpdateConfigurationTest.java, traffic_router/neustar/src/test/java/data/NeustarDatabaseUpdaterTest.java
=> TR fix component scanning and use unique tmp dir names, fixes #1373

traffic_router/core/src/main/webapp/WEB-INF/applicationContext.xml, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/configuration/NeustarConfiguration.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/configuration/TrafficRouterConfigurationListener.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/data/NeustarDatabaseUpdater.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/data/TarExtractor.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/files/FilesMover.java, traffic_router/neustar/src/test/java/configuration/PeriodicUpdateConfigurationTest.java, traffic_router/neustar/src/test/java/data/NeustarDatabaseUpdaterTest.java
fixes #1373
(cherry picked from commit 51703fc6ac623337dbd596a147a01778db1263d3)
=> TR fix component scanning and put neustar data in unique tmp dir

traffic_stats/build/traffic_stats.spec
(cherry picked from commit 8f6e847ebb2061f67ddbc20e5896d20620ac7785)
this fixes #1382
=> Download the 0.11.1 version of influxdb client

traffic_ops/install/bin/postinstall
removes the email you get when it runs.
=> output results of the iso cleanup to dev nulll 

traffic_ops/app/t/api/1.2/deliveryservice_matches.t
=> fixed deliveryservice match test case

traffic_ops/app/db/migrations/20160510082300_add_ds_geo_limit_countries.sql
(cherry picked from commit 8cab602412b5a44bb3b1020fab6922db531e634f)
=> Fix TO db migration comment breaking goose

traffic_ops/app/lib/UI/Cachegroup.pm
Fixes #1432. Also Fixes #1308.
=> TO: allow user to delete parent cache and secondary cache entries

traffic_ops/install/bin/generateCert, traffic_ops/install/bin/postinstall
=> Change rename() to move()

traffic_ops/app/lib/UI/ConfigFiles.pm
=> invalidate content request ttl was always getting set to the ttl_min_hours parameter value

traffic_ops/app/lib/API/Job.pm, traffic_ops/app/lib/UI/Job.pm, traffic_ops/app/templates/tools/invalidate_content.html.ep
=> removes hardcoded min and max invalidate content TTL values

traffic_ops/app/t/api/1.1/job.t
changed expected in test to match value in fixture
=> fix expected ttl limits

traffic_ops/app/lib/TrafficOpsRoutes.pm
=> fixing the profile param api to allow profiles with spaces

traffic_ops/client/type.go
Adding optional param to get data types based on the table they are used in.
fixes #1468
=> Adding optional param 'useInTable'

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java, traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/CoverageZoneTest.java
=> Traffic Router now only returns cache locations supported by given delivery service

traffic_ops/app/conf/cdn.conf, traffic_ops/install/bin/generateCert
RC4 is weak, so remove it from acceptable cipher list
=> RC4 is weak, so remove it

traffic_ops/app/lib/API/DeliveryService/Steering.pm, traffic_ops/app/t/api/1.2/steering_internal.t
Added ability to update and remove filters.
Traffic Ops now returns a 400 (instead of a 200) when you try to update a steering assignment with invalid json.
=> To steering api updates

traffic_ops/app/templates/region/edit.html.ep
=> TO: Allow user to delete region in Traffic Ops

traffic_ops/app/lib/UI/DeliveryService.pm, traffic_ops/app/lib/UI/DeliveryServiceServer.pm
=> Fix #1472: Add config parameters when adding delivery service/ cloning cache server

traffic_server/patches/trafficserver-5.3.2-f914e70.diff
Add the Traffic server 5.3.2 f914e70 diff for inspection.
=> Adding trafficserver-5.3.2-f914e70.diff.

traffic_monitor/experimental/common/poller/poller.go, traffic_monitor/experimental/traffic_monitor/manager/manager.go, traffic_monitor/experimental/traffic_monitor/traffic_monitor.go
Adds publish/Stats endpoint, and the data it requires.
* getStaticAppData() function for start-time known data
* iterationCount channel for HTTP poller
=> Add TM2 publish/Stats endpoint

traffic_ops/app/lib/MojoPlugins/Email.pm, traffic_ops/app/templates/delivery_service/request.mail.ep
=> ldap users can now submit new delivery service requests just like "lo… 

traffic_ops/app/templates/user/registration.mail.ep, traffic_ops/app/templates/user/reset_password.mail.ep
=> removes links to non-existent traffic portal pages

traffic_ops/app/db/migrations/20160613153313_add_guid.sql, traffic_ops/app/lib/API/Server.pm, traffic_ops/app/lib/Schema/Result/Server.pm, traffic_ops/app/lib/UI/Server.pm, traffic_ops/app/templates/server/add.html.ep, traffic_ops/app/templates/server/view.html.ep
feature requested by @dewrich -- Fixes #1520
=> TO: Feature/add server guid

traffic_ops/app/lib/TrafficOps.pm
=> inactivity_timeout setting in cdn.conf was never being respected

docs/source/admin/traffic_stats.rst
=> remove documentation on setting up ssl proxy as it is not needed

docs/source/development/traffic_ops_api/v12/deliveryservice.rst, docs/source/development/traffic_ops_api/v12/profile.rst, traffic_ops/app/lib/API/DeliveryService.pm, traffic_ops/app/lib/API/Profile.pm, traffic_ops/app/t/api/1.2/deliveryservice.t
This is part of resolve for https://github.com/Comcast/traffic_control/issues/1509
=> change REST APIs parameter from snake_case to camelCase

docs/source/development/traffic_ops_api/v12/phys_location.rst, docs/source/development/traffic_ops_api/v12/region.rst, traffic_ops/app/lib/API/PhysLocation.pm, traffic_ops/app/lib/API/Region.pm, traffic_ops/app/t/api/1.2/physlocation.t, traffic_ops/app/t/api/1.2/region.t
change snake_case to camelCase for https://github.com/Comcast/traffic_control/issues/1509
=> REST API snake_case to camelCase

docs/source/development/traffic_ops_api/v12/server.rst, traffic_ops/app/lib/API/Server.pm, traffic_ops/app/t/api/1.2/server_create.t
=> change POST/PUT server API json body keys to camelCase

traffic_ops/app/db/migrations/20160628000000_update_cdn_dnssec_enabled.sql
=> fixing cdn.dnssec_enabled field in the db

traffic_ops/app/lib/API/Cdn.pm
We need to check if the user passed in dnssec_enabled, it is not a required field - the db will default it to 0
=> fix cdn api

traffic_ops/app/lib/UI/Server.pm, traffic_ops/app/templates/navbar.html.ep, traffic_ops/app/templates/server/view.html.ep
=> Traffic Ops now queues updates for an individual server

traffic_ops/install/data/profiles/profile.trafficserver_edge.traffic_ops, traffic_ops/install/data/profiles/profile.trafficserver_mid.traffic_ops
(cherry picked from commit d5dbf0858af2c29f62b435f93a0c639dc794efb6)
=> fixes traffic server version that should be configured by default

traffic_ops/build/traffic_ops.spec
(cherry picked from commit c95df58db3d65f9aa988d5eb12401f8494c804bb)
=> add perl-core to dependencies for Test::More

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/ZoneManager.java
=> Fix TR to continue if a DS regex is invalid.

traffic_ops/app/lib/UI/Topology.pm
(cherry picked from commit 3341414a879a740e044c5397d569abfce350bf91)
=> Adds config->domain_name back into the CRConfig. This resolves #1596.

traffic_ops/app/lib/TrafficOpsRoutes.pm
(cherry picked from commit 353f8dbe0eac67156e19077357416b03cc89aea2)
=> Modified two routes to use relaxed placeholders to fix issue #1598.

traffic_ops/app/lib/UI/Cdn.pm, traffic_ops/app/lib/UI/Parameter.pm
=> Speeds up parameters load

traffic_ops/app/lib/UI/Cdn.pm, traffic_ops/app/lib/UI/Parameter.pm
=> Speeds up fetching of parameters

build/docker-build.sh, traffic_portal/build/Dockerfile, traffic_portal/build/Vagrantfile, traffic_portal/build/build_rpm.sh, traffic_portal/build/traffic_portal.spec
no ant required;  builds using same structure as other rpms.
Fixes #1666
=> Traffic Portal: build without using ant

traffic_monitor/build/Dockerfile, traffic_ops/build/Dockerfile, traffic_portal/build/Dockerfile, traffic_router/build/Dockerfile, traffic_stats/build/Dockerfile
Better to keep images at a known level and update base images with any needed updates.
=> remove yum updates from dockerfiles

traffic_ops/app/lib/API/DeliveryService.pm, traffic_ops/app/lib/UI/DeliveryService.pm, traffic_ops/app/lib/UI/Topology.pm, traffic_ops/app/t/deliveryservice.t, traffic_ops/app/templates/delivery_service/_form.html.ep
Indicates to redirect incoming http traffic to https.
Save protocol value to cr config for TR to consume
=> TO - Add 'http to https' protocol option to Delivery Service

traffic_ops/app/lib/API/Server.pm
=> removes 2 unneccessary database queries - issue #1713

traffic_ops/app/lib/UI/Parameter.pm
=> non-admin user should can't delete the secure parameter

build/docker-build.sh, traffic_router/build/Dockerfile
Installs `which` required by `mvn`.   Also a little cleanup in top-level docker-build.sh.
Fixes #1733
=> fix docker build for traffic_router

traffic_ops/app/lib/UI/DeliveryService.pm
PR #1696 removed this sub which broke at least one config file download endpoint.  This adds it back..
diff below is only to add `sub get_cdn_domain` -- the rest is only whitespace..
Fixes #1735
=> adds previously removed sub get_cdn_domain -- needed by ConfigFiles.pm

traffic_ops/app/lib/UI/UploadHandlerCsv.pm, traffic_ops/app/t_integration/server.t
UploadHandlerCsv and the integration tests were broken due to adding the https port to traffic ops.
=> TO - fix broken integration tests and UploadHandlerCsv

traffic_monitor/experimental/common/fetcher/fetcher.go, traffic_monitor/experimental/traffic_monitor/cache/cache.go, traffic_monitor/experimental/traffic_monitor/deliveryservice/stat.go, traffic_monitor/experimental/traffic_monitor/deliveryservicedata/stat.go, traffic_monitor/experimental/traffic_monitor/http_server/http_server.go, traffic_monitor/experimental/traffic_monitor/index.html, traffic_monitor/experimental/traffic_monitor/manager/datarequest.go, traffic_monitor/experimental/traffic_monitor/manager/events.go, traffic_monitor/experimental/traffic_monitor/manager/healthresult.go, traffic_monitor/experimental/traffic_monitor/manager/lastkbpsstats.go, traffic_monitor/experimental/traffic_monitor/manager/manager.go, traffic_monitor/experimental/traffic_monitor/manager/stathistory.go, traffic_monitor/experimental/traffic_monitor/sorttable.js, traffic_monitor/experimental/traffic_monitor/trafficopsdata/trafficopsdata.go
There were two problems: (1) the EventsThreadsafe type wasn't using pointers, which resulted in set values not propogating, and (2) the GUI was iterating forward, and skipping indices older than the last, but the events array is backwards, so it needs to iterate backwards.
This fixes both.
=> Fix Traffic Monitor 2.0 Events, Fix Kbps

traffic_ops/app/templates/delivery_service/_form.html.ep, traffic_ops/app/templates/delivery_service/index.html.ep, traffic_portal/app/src/common/modules/deliveryService/config/edit/deliveryService.config.edit.tpl.html, traffic_portal/app/src/common/modules/header/header.tpl.html, traffic_portal/app/src/modules/private/dashboard/overview/deliveryServices/DashboardDeliveryServicesController.js, traffic_portal/app/src/modules/private/dashboard/overview/deliveryServices/dashboard.deliveryServices.tpl.html, traffic_portal/app/src/modules/private/deliveryService/view/charts/deliveryService.view.charts.tpl.html, traffic_portal/app/src/modules/private/deliveryService/view/overview/deliveryService.view.overview.tpl.html, traffic_portal/app/src/modules/private/user/user.tpl.html
=> adds dsId to traffic ops UI and traffic portal UI

build/docker-build.sh, traffic_ops/build/Dockerfile
was always defaulting to `master` branch.   Minor change...
=> TO: fix missing env vars on docker run

traffic_ops/app/lib/UI/Parameter.pm
=> Set secure to 0 if the check box secure is un-checked on GUI

traffic_stats/grafana/traffic_ops_cachegroup.js
=> Add connections to cachegroup scripted dashboard

traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/Event.java
=> Fix inconsistency in Traffic Monitor event logging

traffic_monitor/src/test/java/health/DeletemeTest.java, traffic_ops/app/lib/API/Cdn.pm, traffic_ops/app/lib/UI/ConfigFiles.pm
solr search behind riak only returns the first 10 by default and they are not consistently ordered.
=> TO now returns all certs for sslkeys instead of just first 10

docs/source/admin/traffic_vault.rst, traffic_ops/app/lib/API/Cdn.pm, traffic_ops/bin/traffic_ops_ort.pl
Warning!!!!  This version of ORT will ONLY work with Traffic Ops >= 1.7.x which has Traffic Vault and Riak Search enabled.  Documentation here:  https://github.com/Comcast/traffic_control/blob/master/docs/source/admin/traffic_vault.rst
Also updated docs to fix a few formatting issues.
=> Update ORT to use riak search to get SSL Certs

traffic_ops/app/lib/API/Cdn.pm
=> Fix syntax error causing tests to fail

traffic_ops/app/lib/API/Server.pm, traffic_ops/app/lib/UI/Server.pm, traffic_ops/app/lib/UI/UploadHandlerCsv.pm, traffic_ops/app/public/good.csv, traffic_ops/app/templates/upload_server_csv/uploadservercsv.html.ep
=> accounts for new https_port field with upload server csv

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSKeyPairWrapper.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/ds/DeliveryService.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/AbstractServiceUpdater.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/monitor/TrafficMonitorWatcher.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/DataExporter.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/Fetcher.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/PeriodicResourceUpdater.java, traffic_router/keystore/src/main/java/com/comcast/cdn/traffic_control/traffic_router/keystore/KeyStoreHelper.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/data/NeustarDatabaseUpdater.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/data/TarExtractor.java, traffic_router/neustar/src/test/java/data/NeustarDatabaseUpdaterTest.java, traffic_router/neustar/src/test/java/data/TarExtractorTest.java
=> Traffic Router now always cleans up neustar downloads and closes stream resources, fixes #1782

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSKeyPairWrapper.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/ds/DeliveryService.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/AbstractServiceUpdater.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/monitor/TrafficMonitorWatcher.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/DataExporter.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/Fetcher.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/PeriodicResourceUpdater.java, traffic_router/keystore/src/main/java/com/comcast/cdn/traffic_control/traffic_router/keystore/KeyStoreHelper.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/data/NeustarDatabaseUpdater.java, traffic_router/neustar/src/main/java/com/comcast/cdn/traffic_control/traffic_router/neustar/data/TarExtractor.java, traffic_router/neustar/src/test/java/data/NeustarDatabaseUpdaterTest.java, traffic_router/neustar/src/test/java/data/TarExtractorTest.java
Was leaving tarfile entry streams open
Fixes #1782
=> TR now better cleans up stream resources

infrastructure/docker/traffic_ops/Dockerfile
cpan.yimg.com apparently no longer exists.  Removed from docker responses..
=> remove dead cpan repo ref

traffic_ops/app/templates/types/_form.html.ep, traffic_ops/install/data/json/type.json
=> removes ability to create a type for the tm_user table

.gitignore, traffic_ops/client/delivery_service.go, traffic_ops/client/fixtures/delivery_service.go, traffic_ops/client/tests/delivery_service_test.go
This adds various `traffic_ops` `client.DeliveryService*` methods.
=> Delivery service client improvements

traffic_ops/install/bin/postinstall
(cherry picked from commit 9db25c8ccba67be5429fb35ffdc09faefc94a81d)
=> add traffic_portal to list of default profiles this fixes #1830

traffic_ops/app/templates/delivery_service/index.html.ep
(cherry picked from commit 42877d2a103c4102cb382ae62db4d7b1caa8119b)
=> removes ds id from edit/details link

CONTRIBUTORS.md
=> Add Mike Ball to contributors

traffic_monitor/experimental/traffic_monitor/manager/cacheavailablestatus.go, traffic_monitor/experimental/traffic_monitor/manager/dsstats.go, traffic_monitor/experimental/traffic_monitor/manager/events.go, traffic_monitor/experimental/traffic_monitor/manager/healthresult.go, traffic_monitor/experimental/traffic_monitor/manager/lastkbpsstats.go, traffic_monitor/experimental/traffic_monitor/manager/monitorconfig.go, traffic_monitor/experimental/traffic_monitor/manager/opsconfig.go, traffic_monitor/experimental/traffic_monitor/manager/stathistory.go, traffic_monitor/experimental/traffic_monitor/peer/crstates.go, traffic_monitor/experimental/traffic_monitor/trafficopsdata/trafficopsdata.go
=> Change Traffic Monitor 2.0 Mutexes to RWMutex

traffic_ops/client/delivery_service.go, traffic_ops/client/delivery_service_endpoints.go, traffic_ops/client/delivery_service_endpoints_test.go
This PR is dependent on Pull Request #1845 . If/when PR 1845 is merged, I can rebase & force push this `dry-client` branch.
=> Dry client

traffic_monitor/experimental/traffic_monitor/manager/dsstats.go
=> Fix TM2 concurrent map writes

traffic_router/keystore/src/main/java/com/comcast/cdn/traffic_control/traffic_router/keystore/KeyManager.java
=> TR no longer reverses the order of the certificate chain.  

traffic_ops/app/lib/UI/Server.pm
* traffic_ops/app/lib/UI/Server.pm
This should fix the 'no reply' and 500 error that was being returned when trying to clear the update column in TO.
fixes #1238
=> Change render_text to render( text => for sub postupdate in Server.pm

traffic_ops/app/lib/UI/Server.pm, traffic_ops/app/t_integration/server.t
=> joins server with profile table to ensure ip and ip6 are unique to profile

traffic_monitor/experimental/traffic_monitor/manager/manager.go, traffic_monitor/experimental/traffic_monitor/manager/opsconfig.go, traffic_monitor/experimental/traffic_monitor/trafficopswrapper/trafficopswrapper.go
=> Fix TM2 CRConfig endpoint

traffic_monitor/experimental/traffic_monitor/manager/datarequest.go
=> Add TM2 memory, goroutines to stats endpoint

traffic_monitor/experimental/traffic_monitor/manager/cacheavailablestatus.go, traffic_monitor/experimental/traffic_monitor/manager/dsstats.go, traffic_monitor/experimental/traffic_monitor/manager/events.go, traffic_monitor/experimental/traffic_monitor/manager/healthresult.go, traffic_monitor/experimental/traffic_monitor/manager/lastkbpsstats.go, traffic_monitor/experimental/traffic_monitor/manager/monitorconfig.go, traffic_monitor/experimental/traffic_monitor/manager/stathistory.go, traffic_monitor/experimental/traffic_monitor/peer/crstates.go
Reduces mutex contention, by changing getters and setters to not copy values, but only set pointers.
=> Traffic Monitor 2.0 Mutex Contention Improvements

traffic_monitor/experimental/traffic_monitor/http_server/http_server.go, traffic_monitor/experimental/traffic_monitor/manager/datarequest.go
=> Fix TM2 request errors to return 500

traffic_stats/traffic_stats.go
This was causing TS to panic.  This fixes #1458
=> don't set client to nil after attempting to ping server

docs/source/development/traffic_ops_api/v12/profile.rst, traffic_ops/app/lib/API/Profile.pm, traffic_ops/app/lib/TrafficOpsRoutes.pm, traffic_ops/app/t/api/1.2/profile.t
=> Add new RESTful API: profile (edit/delete)

traffic_monitor/experimental/traffic_monitor/cache/cache.go, traffic_monitor/experimental/traffic_monitor/http_server/http_server.go, traffic_monitor/experimental/traffic_monitor/index.html, traffic_monitor/experimental/traffic_monitor/manager/datarequest.go
=> Add TM2 /api/bandwidth-capacity endpoint

traffic_monitor/experimental/traffic_monitor/index.html
=> Add TM2 GUI CDN name

traffic_monitor/experimental/traffic_monitor/manager/healthresult.go, traffic_monitor/experimental/traffic_monitor/manager/monitorconfig.go, traffic_monitor/experimental/traffic_monitor/manager/peer.go, traffic_monitor/experimental/traffic_monitor/peer/crstates.go
=> Fix CRStates endpoint deliveryServices

docs/source/development/traffic_ops_api/v11/cachegroup.rst, docs/source/development/traffic_ops_api/v12/cachegroup.rst, traffic_ops/app/lib/API/Cachegroup.pm, traffic_ops/app/lib/TrafficOpsRoutes.pm
=> adds api/cachegroups/:id endpoint

docs/source/development/traffic_ops_api/v11/profile.rst, docs/source/development/traffic_ops_api/v12/profile.rst, traffic_ops/app/lib/API/Profile.pm, traffic_ops/app/lib/TrafficOpsRoutes.pm
=> adds /api/version/profiles/:id api endpoint

traffic_stats/traffic_stats.go
should be log.Errorf() not log.Error()
=> fix incorrect logging method

traffic_monitor/experimental/traffic_monitor/config/config.go, traffic_monitor/experimental/traffic_monitor/traffic_monitor-example-config.json, traffic_monitor/experimental/traffic_monitor/traffic_monitor.go
=> Add TM2 log location config

traffic_monitor/experimental/traffic_monitor/index.html
=> Fix TM2 GUI max kbps

traffic_monitor/experimental/traffic_monitor/manager/manager.go, traffic_monitor/experimental/traffic_monitor/manager/monitorconfig.go, traffic_monitor/experimental/traffic_monitor/traffic_monitor.go
=> Fix TM2 PeerStates to exclude self

docs/source/development/traffic_ops_api/v11/status.rst, docs/source/development/traffic_ops_api/v12/status.rst, traffic_ops/app/lib/API/Status.pm, traffic_ops/app/lib/TrafficOpsRoutes.pm
=> adds /api/statuses/:id api endpoint

traffic_monitor/experimental/traffic_monitor/index.html
Adds highlighting offline events red in the web GUI.
Changes event availability text to offline/available instead of true/
false.
Fixes #1976
=> Add TM2 GUI event highlighting, availability text

traffic_ops/app/lib/TrafficOpsRoutes.pm
=> eliminate .json suffix on remaining api calls

traffic_monitor/experimental/traffic_monitor/index.html
=> Change TM2 GUI bandwidth to more readable units

traffic_monitor/experimental/traffic_monitor/cache/cache.go, traffic_monitor/experimental/traffic_monitor/health/cache_health.go, traffic_monitor/experimental/traffic_monitor/manager/healthresult.go
Fixes Traffic Monitor 2.0 event log description to include HTTP fetch
errors.
Fixes broken print formatting.
Changes Result to only have one error. Once an error occurs, that
error should be passed up, and we shouldn't try to do any more
processing on the result.
Fixes #1975
=> Fix TM2 event log to include error details

docs/source/admin/traffic_stats.rst, docs/source/development/traffic_stats.rst, docs/source/overview/traffic_stats.rst
Also cleaned up spelling errors, grammar errors (there are sure to be more), and hard to understand sentences.
=> Updated Traffic Stats docs to reflect changes for 1.8

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/secure/CertificatesClient.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/secure/CertificatesPoller.java, traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/secure/CertificatesPublisher.java, traffic_router/core/src/main/webapp/WEB-INF/applicationContext.xml
timestamps relating to last check time, last success for fetching, last valid/invalid certificates
=> Traffic Router crs/stats endpoint now contains data about https certificates
