Comcast/traffic_control

traffic_ops/app/lib/UI/GenIso.pm

Instead of directly editing ks.src into ks.cfg, this change will write three files: disk.cfg, network.cfg and password.cfg. 
Additionally this change uses crypt to hash a provided password (Also sets a default if no password is provided. The default in the code is "Fred".) 
password.cfg is straight-up included into ks.cfg as an %include file. 
disk.cfg and network.cfg are intended to be processed by scripts.

Change the way GenISO creates images. 

---

traffic_ops/bin/traffic_ops_ort.pl

Jan and I very, very briefly discussed this--when traffic_ops_ort runs they all run on the 15 and all delay 5 seconds, which means they all hit more-or-less at once. 
sleep_rand didn't have any rand in it, so I made it randier.

This changes the fixed duration to a random duration.

---

traffic_ops/rpm/build/build_rpm.sh

This will tag the release according to this format: traffic_ops-release-1.x

changed the tag release format to accommodate traffic ops

---

docs/source/development/traffic_ops.rst

Steps 4 and 6 were the same step; also, the numbering was off.

Modified steps in setting up traffic ops

---

traffic_ops/app/db/migrations/20150530100000_add_any_remap.sql

The migration was trying to insert a description of 75 characters when the max was 45

updated migration to expand size of description column on type table

---

traffic_ops/install/bin/postinstall

PERL5LIB not set early enough, so download_web_deps fails silently with missing dependencies

move PERL5LIB setting further up for all cmds

---

traffic_ops/install/lib/InstallUtils.pm

download_web_deps error was masked by this.   Error will look something like this:
Running [/sbin/service traffic_ops start]...
ERROR: /sbin/service traffic_ops start failed

make exec failures visible using IPC::Cmd instead of fork/exec

---

docs/source/admin/quick_howto/multi_site.rst

I've updated the traffic control documentation for the multi-site origin configuration.  On the delivery services details page, in addition to checking the multi-site origin feature to yes, make sure that the Content Routing type is set to HTTP_LIVE_NATL.  If this is not done, requests will be routed directly to the parent instead of the MID tier cache where the multi-site parent selection is configured.
We found this issue while testing the configuration Jan had written up.

Modified the configuration info for the multi-site origin feature.

---

traffic_ops/install/bin/postinstall

this error was hidden until redo of executeCommand. /usr/bin/stty is incorrect on CentOS.  'stty echo' not needed because promptUser resets echo.

remove stty call -- wrong path and not needed

---

traffic_ops/app/lib/TrafficOps.pm

fixes problems with tests where conf files not found:
.../traffic_ops/app/t/aadata.t/../conf/cdn.conf Not a directory

find conf path using module path, not executable

---

traffic_ops/app/lib/UI/ConfigFiles.pm

I tested over 1.1.3 but couldn't test with master. This fix is trivial that should be fine.
I didn't add the "background fetch" for Mid handling but it should probably be there as well. If that's required let's create a new issue. 
Fixes #391

Adding Mid remap line for cache_range_request plugin

---

traffic_ops/app/lib/TrafficOps.pm

Closes #387.  Don't return a token for user if role is 'disallowed'

if user is disallowed, don't return credentials

---

traffic_ops/app/lib/MojoPlugins/TrafficMonitorConnection.pm

Fixes #322 - logging error using carp/cluck instead of carp/confess.
carp/confess shows a backtrace but is fatal.  carp/cluck shows a backtrace but is not fatal.

Fixes #322 - logging error using carp/cluck instead of carp/confess.

---

traffic_ops/app/templates/server/add.html.ep

A cachegroup id is stashed when you create a new serve.  When a error is returned the javascript is comparing the stashed cachegroup id to a cachegroup name so there is never a match.  Updated the code to compare the stashed value to the cachegroup id.

Fixes #328 - stashing cachegroup value when creating new server

---

traffic_ops/rpm/build/build_rpm.sh

jenkins wasn't showing failed status because script continued on after ant failure

exit with bad status if ant fails

---

traffic_ops/app/bin/checks/IPv6.pm
traffic_ops/app/bin/checks/ToDSCPCheck.pl

1. traffic_ops/app/bin/checks/IPv6.pm - new file, cannot be installed
by CPAN.
2. traffic_ops/app/bin/checks/ToDSCPCheck.pl
* added IPv6 checking
* incremented version
* removed $hostn
* changed the way autoflush is handled
* added $cms_int var now required on the command line in jconf
* removed $match because it was not being used
* added $chck_lng_nm for syslog messages
* I was going to put in to have it fail if the ‘checkPath’ wasn’t
defined but, opted not to. Left the code in but commented.
* changed curl to use the -H option and the url now uses the IP
address
* changed get_dscp to also return -1 so that if we can’t connect to
the server we will know.
* added trim functions.

added syslog and IPv6 checking to ToDSCPCheck.pl

---

traffic_ops/app/bin/checks/ToORTCheck.pl

* added example cron entries
* removed $username = “jvando001”
* incremented version
* removed $hostn
* added -h option
* added help()
* re-ordered beginning so that script would error quicker if command line vars
were incorrect
* added $chck_lng_nm for syslog messages
* added $to_user and $to_pass for ORT script on remoter server
* removed $match and $select
* added code to get Traffic Ops URL from TO API
* changed the ssh command to include the $to_url, $to_user, and $to_pass
* added 2>&1 to ssh command so that I could check if ssh was unable to
connect to server (added -1 for the ORT column in TO)
* Will now output results to /var/www/html/\<host_id\>/results (this file
gets overwritten each time the script is run)
* ERRORS, FATALS, and WARNS are calculated for syslog messages
* only …

Add syslog messages to ToORTCheck.pl

---

traffic_ops/app/lib/API/Job.pm
traffic_ops/app/t/api/1.1/job.t

This addresses one other part of #491 : 
previous request used an alert (400) where it should have used forbidden (403)

use forbidden rather than alert for creating purge job

---

docs/source/admin/traffic_stats.rst
docs/source/overview/traffic_stats.rst
traffic_stats/traffic_stats.cfg

Documentation is now more comprehensive.  Provided all information that should be needed to configure traffic stats, grafana, and influxdb.  Provided all information that should be needed to configure integration between traffic stats (grafana) and Traffic Ops.

Updated Traffic Stats Documentation

---

traffic_ops/app/lib/Extensions/TrafficStats/Delegate/Statistics.pm

Change for #515: Currently assumes interval size is 10s -- this allows an extension to override that.

allow extension to override interval size

---

docs/source/admin/traffic_ops_using.rst
traffic_ops/app/lib/UI/DeliveryService.pm
traffic_ops/app/lib/UI/DnssecKeys.pm
traffic_ops/app/lib/UI/Utils.pm
traffic_ops/app/templates/dnssec_keys/add.html.ep
traffic_ops/app/templates/dnssec_keys/addksk.html.ep
traffic_ops/app/templates/dnssec_keys/manage.html.ep

The Activate key is only visible if keys exist, this is to help prevent issues that could occur if a user activiates DNSSEC for a CDN before creating DNSSEC keys.
Updated language used on confirm keys for generating and regenerating keys. A user should now be more clear as to the implications of creating or recreating the keys.
Create DNSSEC keys for a new delivery service if DS is part of a CDN with DNSSEC enabled

DNSSEC UI changes

---

traffic_ops/app/lib/UI/ConfigFiles.pm

#556 - when generating conf files for mid,  goes thru all rascal and edge servers to get ip addresses.  This error happened when one of those servers had no ip6 address defined.

#556 skip ip6_address if not defined

---

docs/source/admin/quick_howto/multi_site.rst
docs/source/admin/traffic_ops_install.rst
docs/source/admin/traffic_stats.rst
docs/source/development/traffic_ops.rst
docs/source/development/traffic_ops_api/v11/to_extension.rst
docs/source/development/traffic_ops_api/v11/user.rst
docs/source/development/traffic_ops_api/v12/to_extension.rst
docs/source/development/traffic_ops_api/v12/user.rst

many .rst docs had multi-byte smart quotes instead of normal ascii versions.   That causes problems when copying an example command from a web browser to a command line, e.g.
```
mysql> create user ‘to_user’@’localhost’;
```
I don't know exactly how to generate the docs html from .rst,  but this ought to fix that issue..

change out multi-byte "smart quotes" in docs for simple ascii version

---

traffic_ops/rpm/traffic_ops.spec

Fixes #529. Moved "service ... stop" to pre-uninstall section so service is stopped cleanly before files are removed.

stop service before uninstall starts

---

.gitignore
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/AbstractServiceUpdater.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/Federation.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationMapping.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationMappingBuilder.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationsBuilder.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationsWatcher.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/NetworkNode.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/CidrAddress.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/Fetcher.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/ProtectedFetcher.java
traffic_router/core/src/main/resources/applicationContext.xml
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationMappingBuilderTest.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationsBuilderTest.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/util/FetcherTest.java
traffic_router/core/src/test/resources/cache.properties

Traffic Router now polls Traffic Ops for federated coverage zone data

Traffic Router support for ingesting and parsing a secondary CZF file

---

traffic_ops/app/lib/UI/Profile.pm

profile dropdown does not render when a profile does not have a cdn_name.  now checking if cdn_name exists.

fix profile_dropdown when creating a server

---

traffic_stats/traffic_stats.init

Apparently we still need the &. Also redirect everything to /dev/null since we don't print anything important not to a log.

Fix traffic_stats init script startup

---

traffic_stats/traffic_stats.go

Revert "Missed one time format change"
This reverts commit 9fba1ae1eb4a5c34e2715a32555d436f6b3dbd14.

MySQL does not use a standard time format

---

traffic_ops/app/lib/Fixtures/Type.pm

this entry was missing in the Type fixture -- caused several unit tests to fail.

add missing ANY_MAP entry to Type fixture

---

docs/source/admin/traffic_stats.rst

Please review. 
- I removed some mention of Grafana 2.0.2
- added the new scripts in the table at the bottom
- added notes for httpd configuration

Traffic Stats documentation updated related to scripted dashboards

---

docs/source/admin/traffic_stats.rst
traffic_stats/traffic_stats.spec

Updated the Spec file to copy the Grafana custom dashboard files into place as part of the RPM install process.
Updated the Traffic Stats admin docs to reflect the change.

Traffic Stats Spec file and documentation

---

traffic_ops/app/lib/TrafficOps.pm

Doesn't affect function of secrets,  only warning message for cdn.conf.

cdn.conf validation checks for secrets instead of shared_secret

---

traffic_ops/app/db/migrations/20151014094910_update_ds_cdn_id.sql

adding new migration to ensure that cdn_id is not null in the delivery service table.

update delivery service cdn_id

---

traffic_ops/app/db/migrations/20151014094910_update_ds_cdn_id.sql

adding new migration to ensure that cdn_id is not null in the delivery service table.

updating delivery service cdn_id

---

traffic_stats/traffic_stats.init

Thinking that when we crash we'll get more useful information this way.

Redirect stdout and stderr to a log file

---

traffic_ops/client/traffic_ops.go

> $ go get github.com/Comcast/traffic_control/traffic_ops/client
> warning: code.google.com is shutting down; import path code.google.com/p/go.net/publicsuffix will stop working
https://godoc.org/golang.org/x/net/publicsuffix

Remove reference to code.google.com repo

---

docs/source/admin/traffic_ops_install.rst

Feels like the doc is out-dated, some are misleading.
traffic_ops package is not available in any default yum repositories that come with CentOS.
Step 3 has been implemented in the installer ever since the init commit.

update traffic_ops install doc

---

traffic_ops/install/go/src/comcast.com/dataload/dataload.go

Fixes #656 for release 1.2.0 - cdn_id was removed from profile table, but not dataload.go.

remove cdn_id from profile in dataload

---

traffic_ops/install/bin/generateCert
traffic_ops/install/bin/postinstall
traffic_ops/install/lib/InstallUtils.pm

Fixes #614 (generateCerts overwrites cdn.conf) and makes postinstall generally more consistent handling config files.   Should make it easier to fully automate checking for existing installation and updating only what's necessary.

Postinstall prompts

---

traffic_ops/rpm/build/build_rpm.sh

previous version included go src dependencies in the rpm.  This builds go execs and delivers only the binaries to install/bin.

TO rpm: 'go get' in src dir  -- not in rpmbuild

---

traffic_router/core/pom.xml
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/cache/Cache.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java

The improved TPS score will be even better with proper hostnames in the dns request from PR 730
https://github.com/Comcast/traffic_control/pull/730
The minimum TPS score should be adjusted as soon as both are merged.

Improve cache selection performance

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/AbstractProtocol.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/TCP.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/UDP.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/AbstractProtocolTest.java

application log, It's already recorded in the access log

Remove Wire Parse Exception logging entries from Traffic Router

---

traffic_ops/app/lib/Extensions/TrafficStats/API/CacheStats.pm
traffic_ops/app/lib/MojoPlugins/Stats.pm
traffic_ops/app/lib/TrafficOpsRoutes.pm
traffic_ops/app/lib/UI/VisualStatus.pm
traffic_ops/app/templates/visual_status/graphs.html.ep

Current Bandwidth, Current Connections, and percentage of capacity used per CDN is now visible on the visual status page (Health -> graph view).  This replicates the functionality that was available in the redis graphs page using influxdb.

Add current bandwidth, connections, and percentage of capacity to graphs in TO.

---

traffic_ops/app/lib/API/DeliveryService.pm

Fixes #53 
As suggested,  json output now contains { "exampleURLs": [ ...] }.    Used the method from UI::DeliveryService.

make get_example_urls available to DS api

---

traffic_ops/app/lib/API/Cdn.pm
traffic_ops/app/lib/UI/Cdn.pm
traffic_ops/app/lib/UI/Topology.pm

I noticed several warnings during test in traffic_ops (prove -qrp t).   Use of uninitialized vars, useless use of scalar ref,   "assuming CORE::index..."...   Changes were minor -- these are fixed and prove (and dev console msgs) is less noisy.

TO: fixes warnings

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationMapping.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationMappingBuilder.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationMappingBuilderTest.java

Initialize federation resolvers as empty ComparableTreeSets to avoid NPEs

---

traffic_monitor/build/build_rpm.sh
traffic_monitor/pom.xml
traffic_router/api/pom.xml
traffic_router/build/build_rpm.sh
traffic_router/build/pom.xml
traffic_router/connector/pom.xml
traffic_router/core/pom.xml
traffic_router/pom.xml
traffic_router/testServer/pom.xml

rpm will now be named from content of VERSION file.  This should be included in the 1.3.x release.
This fixes #803

use $traffic_control.version for traffic_router version

---

traffic_ops/install/bin/web_deps.txt

the jMenu files were already included in the delivered rpm,  so not necessary in web_deps.txt.
Fixes #810

remove jmenu entries -- were removed from original source repo

---

traffic_monitor/pom.xml

some of its downstram dependencies are interfering with successful maven builds

Exclude wicket-atmosphere transitive dependency from Traffic Monitor

---

traffic_monitor/pom.xml

some of them are interfering with successful maven builds
(cherry picked from commit 883db3a61f67eed0ae150239026fb5f64a44c19c)

Exclude unnecessary transitive dependency wicket-atmosphere from Traffic Monitor

---

traffic_monitor/.gitignore
traffic_monitor/src/main/conf/log4j.properties
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/CacheState.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/CacheWatcher.java

After lots of testing we found that we can set the health.timepad configuration to 0 and found an improvement by not cancelling already cancelled java future tasks

Traffic monitor scaling

---

traffic_ops/app/lib/Fixtures/Cachegroup.pm

avoids fk constraint violation if fixtures inserted in wrong order

guarantee order of cachegroup fixture db insertion

---

traffic_ops/app/lib/UI/DeliveryService.pm

Fixes #884.  Before checking the rest of the delivery service form, check if xml_id already exists...

check for existing xml_id before adding ds

---

traffic_stats/build/traffic_stats.spec

lock on influxdb v0.9.4 api

---

traffic_ops/etc/init.d/traffic_ops

Changes init to match on /traffic_ops\/app\/script\/cdn/  instead of just traffic_ops. This prevents too many results from being returned in the awk when there is a mount point containing the name traffic_ops. 
also changed awk to /bin/awk to be more consistent.

make startup more specific

---

docs/source/admin/traffic_stats.rst
traffic_stats/influxdb_tools/README.txt
traffic_stats/influxdb_tools/create_ts_databases.go
traffic_stats/influxdb_tools/sync_ts_databases.go
traffic_stats/traffic_stats.cfg

Added influxdb_tools which contains go scripts: create_ts_databases.go and sync_ts_databases.go.
**create_ts_databases.go** creates all databases, retention_policies, and continuous queries used by traffic_stats.  The continuous queries help make the grafana graphs much faster and allow to easily keep more than a days worth of data. 
**sync_ts_databases.go** provides the ability to sync Traffic Stats continuous query data from one environment to another.

Scripts for Creating and Syncing Traffic Stats Databases

---

traffic_ops/app/templates/cachegroup/view.html.ep

fixes #934 .   view template was referencing old variable names.   Will only happen when user has only read-only

use correct var names in CacheGroup view template

---

traffic_ops/app/lib/UI/Cdn.pm

The Servers Page was querying the DB for the URL of graphing server once for each server to display the link for the graph for that server. This change just makes it do the lookup once.

Speed up display of the Servers Page

---

traffic_ops/app/lib/UI/Topology.pm

Fixes #944.   An even number of matching profiles caused "Odd number of elements..." warning which led to  incorrect DBIX query.
This should be pulled into a new 1.3.0-RC?

use ref for hash value

---

docs/source/admin/traffic_stats.rst
traffic_stats/influxdb_tools/create_ts_databases.go
traffic_stats/influxdb_tools/sync_ts_databases.go
traffic_stats/traffic_stats.go

This closes #956.
InfluxDb will need to be upgraded to version 0.9.6 or above to support the client change.

Updated Traffic Stats to use v2 version of Influxdb Client

---

traffic_ops/app/lib/Extensions/TrafficStats/API/CacheStats.pm
traffic_ops/app/lib/TrafficOpsRoutes.pm
traffic_ops/app/templates/visual_status/graphs.html.ep
traffic_stats/grafana/traffic_ops_cachegroup.js
traffic_stats/grafana/traffic_ops_deliveryservice.js
traffic_stats/grafana/traffic_ops_scripted.js
traffic_stats/grafana/traffic_ops_server.js

Since the continuous queries are now created when running traffic_stats/influxdb_tools/create_databases, the dashboards can be updated to use the continuous queries as well.
Also removed the individual internal APIs that were used to populate the graphs table and replaced with a single API call.

Updated scripted dashboards to use continuous queries

---

traffic_ops/app/db/create_tables.sql

#964 modified create_table.sql to remove local_user,  but that's not necessary because there's a migration that drops the column.   ```db/admin.pl reset``` gives me this: 
2016/01/23 00:32:07 FAIL 20160102193037_drop_local_user.sql (Received #1091 error from MySQL server: "Can't DROP 'local_user'; check that column/key exists"), quitting migration.
The column needs to exist for the migration to drop it..

revert change only to create_table.sql

---

traffic_ops/install/go/src/comcast.com/dataload/dataload.go

This fixes postinstall failing to add the Traffic Ops user to SQL.
Fixes #990

Fix Traffic Ops dataload.go extra SQL parameter

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessEventBuilder.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java

Also log error if a cache group with a location of 0.0,0.0 is selected during Geo lookup

Fix lat,long formatting in Traffic Router Access Log

---

docs/source/admin/traffic_router.rst
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/http/HTTPAccessEventBuilder.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java

and log an error if a cache group with a location of 0.0,0.0 is selected during Geo lookup
(cherry picked from commit a06b20443078c19a4726104b88af3c38f4cfba1d)

Fix formatting of lat,long in traffic router access log 

---

traffic_stats/build/traffic_stats.spec
traffic_stats/influxdb_tools/README.txt
traffic_stats/influxdb_tools/create_ts_databases.go
traffic_stats/influxdb_tools/sync_ts_databases.go
traffic_stats/traffic_stats.go

The spec file will now build with the master branch of InfluxDb, because I could not getting working with a specific branch due to the github repo moving.  I suspect that once a new tag is created by influxdb we can make this work again.

This updates traffic stats to use the new github repo for influxdb (github.com/influxdata)

---

traffic_monitor/build/build_rpm.sh
traffic_router/build/build_rpm.sh

Added clean to the mvn goals in the build scripts for TR and TM.  This fixes an issue we were seeing where a build on a branch would fail if master had been previously built.

Update mvn goals in TM and TR builds

---

traffic_monitor/build/build_rpm.sh
traffic_router/build/build_rpm.sh

Updated the build script for TR and TM to do a "clean" before doing a "package".  The prevents issues from occurring when multiple builds are happening from the same location (such as in a ci environment).
(cherry picked from commit 622937edbaa2d347d4e6ef3f292e27cf5b90c2bc)

Update mvn goals in TR and TM build script

---

traffic_ops/install/bin/web_deps.txt

use http for code.jquery -- works around curl version issue on centos 6

---

traffic_monitor/README.md
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/MonitorApplication.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/config/ConfigHandler.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/config/RouterConfig.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/AbstractState.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/CacheWatcher.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/DsState.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/EmbeddedStati.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/Event.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/HealthDeterminer.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/PeerState.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/publish/CacheStats.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/publish/CrStates.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/util/PeriodicResourceUpdater.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/CacheListPanel.html
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/CacheListPanel.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/DsListPanel.html
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/DsListPanel.java
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/EventLogPanel.html
traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/wicket/components/EventLogPanel.java
traffic_monitor/src/test/java/com/comcast/cdn/traffic_control/traffic_monitor/Start.java
traffic_monitor/src/test/java/com/comcast/cdn/traffic_control/traffic_monitor/TestHomePage.java
traffic_monitor/src/test/java/config/ConfigHandlerTest.java
traffic_stats/traffic_stats.go

Add cache type to Traffic Stats and Traffic Monitor; fixes a config file path issue and reduces logging.

---

traffic_monitor/build/build_rpm.sh
traffic_monitor/pom.xml
traffic_router/api/pom.xml
traffic_router/build/build_rpm.sh
traffic_router/build/pom.xml
traffic_router/connector/pom.xml
traffic_router/core/pom.xml
traffic_router/pom.xml
traffic_router/testServer/pom.xml

Fixes #1080 and should still support our build_rpm.sh

Router and Monitor no longer require TRAFFIC_CONTROL_VERSION env var to run maven

---

traffic_ops/app/lib/MojoPlugins/DeliveryService.pm

fixes #1089, #1090 
blank params should get undef unless another default value is specified

if param is blank, accept default passed instead

---

traffic_ops/install/bin/postinstall

Fixes Traffic Ops postinstall to not create default profiles and
parameters when doing an upgrade instead of a clean install. More
specifically, if non-default profiles exist defaults are not imported.
Fixes #1095

Fix postinstall to not create defaults on upgrade

---

traffic_ops/app/lib/UI/ConfigFiles.pm

bypass strict check when loading extension thru ConfigFiles.pm

no strict refs when invoking extension sub

---

traffic_ops/app/lib/UI/ConfigFiles.pm

a blank origin can cause the parent.config to not get loaded.  This avoids that problem.

parent.config -- skip line if no remap origin

---

traffic_ops/experimental/server/auth/auth.go

It was calling err.Error() even when `err` was nil, namely when the
password was wrong but no error was returned.

Fix TO 2.0 nil reference

---

traffic_ops/experimental/ats_config/ats_config.go
traffic_ops/experimental/ats_config/configfiles.go
traffic_ops/experimental/ats_config/trafficops.go

This service acts as a 'microservice' and serves ATS config files, by querying the Traffic Ops API.
This currently only creates storage.config, as a proof-of-concept. But it has the framework to easily add the rest of the configs. If we decided not to do the microservice thing, the config file logic easily be adapted to a library within a larger service. In fact, it would probably be good to make it a package anyway.

Add Traffic Ops 2.0 service to get ATS configs

---

docs/source/admin/traffic_stats.rst
traffic_stats/grafana/traffic_ops_cachegroup.js
traffic_stats/grafana/traffic_ops_deliveryservice.js
traffic_stats/grafana/traffic_ops_scripted.js
traffic_stats/grafana/traffic_ops_server.js

While doing some QA I found some issues with the scripted dashboards, so I fixed them.  I also updated the traffic stats documentation to use the correct URLs that grafana now uses for solo dashboards (as of 2.1.x, latest is 2.6.x).

Traffic Stats scripted dashboard updates

---

traffic_router/api/pom.xml
traffic_router/build/pom.xml
traffic_router/core/pom.xml
traffic_router/pom.xml

Update to spring framework 4.2.5, does not require upgrading to anything newer than Java 6

Update Traffic Router to latest version of Spring Framework

---

docker/Traffic_Server_Edge_Dockerfile
docker/Traffic_Server_Edge_Dockerfile_run.sh
docker/Traffic_Stats_Dockerfile
docker/Traffic_Stats_Dockerfile_run.sh
docker/Traffic_Vault_Dockerfile
docker/Traffic_Vault_Dockerfile_run.sh

This adds Grafana and Heka to the Dockerfiles, and fixes the Traffic Vault Dockerfile to listen on 0.0.0.0.

Dockerfile fixes

---

docs/source/admin/traffic_router.rst
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/ds/DeliveryService.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/request/RequestMatcher.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/StatTracker.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandlerTest.java

In the past, if the Geolimit check fails (for example, the client ip is not in the 'US' region but the geolimit is set to 'CZ + US'), the router will return 503 response; but with this feature, when the check fails, it will return 302 if the redirect url is set in the delivery service.
The Geolimit check failure has such scenarios:
1) When the geolimt is set to 'CZ + only', if the client ip is not the the CZ file, the check fails
2) When the geolimit is set to any region, like 'CZ + US', if the client ip is not in such region, the check fails
And different configured redirect urls have different meanings:
1. If no domain is in the url (like 'vod/dance.mp4'), the router will try to find a proper cache server and return  the redirect url with the format like '`http://<cache server …

add Geolimit failure redirect feature (short for NGB)

---

traffic_stats/traffic_stats.go

I will need to create a 1.4.1 release.  How I let this make it through 10 RCs I do not know.
(cherry picked from commit e88fd0b53718d8e0dc37fb6abe0d1ef9d06099a7)

BACKPORT -- fix issue with daily_maxgbps being written as daily_bytesserved

---

traffic_stats/traffic_stats.cfg
traffic_stats/traffic_stats.go

Can be configured by the following value to /opt/traffic_stats/traffic_stats.cfg `"influxProtocol": "http"`.
If no protocol is defined in the config, Traffic Stats will default to http.
In order for https to work you need a "real" cert.  Trying to use a self-signed cert results an error like: `[ERROR] 2016-03-16 15:51:10 Get https://localhost:8086/query?db=&q=show+databases: x509: certificate signed by unknown authority`
For influxdb configuration questions, see the influxdb documentation.
this closes #1143

Add support for http, https, and udp protocols to Traffic Stats

---

traffic_ops/app/lib/MojoPlugins/Response.pm
traffic_ops/app/lib/UI/ConfigFiles.pm

In ConfigFiles.pm, if the response coming back from method called by dispatch table starts with Error, send a 500 response
(cherry picked from commit a864693e7b44dc2775f77a7161505ae1265f6f3a)

BACKPORT - Return a 500 response if an Error is encountered in ConfigFiles.pm

---

traffic_ops/app/lib/UI/DeliveryService.pm

This should have been cherry-picked earlier.   Resolves the "Odd number of elements..." error message and not saving updated deliveryservice.

fix deliveryservice type references

---

traffic_ops/experimental/server/api/server_byname.go
traffic_ops/experimental/server/api/tm_user_byname.go
traffic_ops/experimental/server/crconfig/crconfig.go
traffic_ops/experimental/server/routes/routes.go

This fixes several error return issues.
`GetServerByName` was logging errors, but continuing anyway and trying to index the nil slice.
`GetCRConfig` was only checking and returning the last error, not every error for every function called.
Routes for both the `crconfig` and `csconfig` were ignoring errors and returning the value anyway. This fixes to return a JSON object with an `error` key, with the error string.

TO 2.0 API error return fixes

---

traffic_ops/install/bin/postinstall

Fix postinstall prompting for TO user every time

---

traffic_ops/app/lib/UI/ConfigFiles.pm

Fixes Traffic Ops remap.config generation to add the port to HTTP
delivery service remap rules, if it's nonstandard. This fixes the Host
headers generated by ATS to conform to RFC 2616, and fixes the CDN to
work with edges with nonstandard ports.
Fixes #1134

Fix TO remap rules for nonstandard ports

---

traffic_ops/install/data/json/status.json

The PRE_PROD status was being added by both `dataload.go` via `status.json`, and a Goose migration. Since the migration will always run on both new installs and upgrades, removing it from `dataload` seems like the right solution.
I looked into letting both dataload and the migration insert it with `insert ignore` (so `status.json` could sort of act as documentation of the statuses), but the PK is an ID, not the name, so there's no way to do that without a nontrivial query or schema modification.
Fixes #950

Fix TO duplicate PRE_PROD on new install

---

traffic_stats/build/traffic_stats.spec
traffic_stats/influxdb_tools/create_ts_databases.go
traffic_stats/influxdb_tools/sync_ts_databases.go

This closes #1069 
create_ts_databases and sync_ts_databases are now included with the traffic stats build.  This gives users the ablilty to run them without having to have a golang dependency and without needing to checkout the code, build them, etc. 
Also fixed an issue where the tools were trying to continue when the client was not created successfully giving the appearance that they were successful when really they were not.

Added InfluxDb tools to RPM build

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandlerTest.java

Removed System.out.printlns from test.
Made the logging less noisy.
This closes #1184

Remove noisyness from ConfigHandlerTest

---

traffic_ops/install/bin/generateCert

This changes postinstall (generateCerts) to prompt the user if openssl
fails, whether they want to retry.
Ideally, we would immediately inform and retry mismatched passes, but
that isn't possible while calling openssl as an external app.
We would also ideally always retry, except exit if the user hit
ctrl+c. But openssl doesn't return different exit codes for SIGINT
versus failures. Thus, asking seems like the most reasonable option.
Fixes #1063

Fix TO postinstall to retry failed openssl calls

---

traffic_ops/app/lib/UI/ConfigFiles.pm
traffic_ops/app/lib/UI/DeliveryService.pm

Fixes #752
Removing remap rules makes me anxious, so, just to confirm this is the right thing to do: this removes _**all**_ rules in `remap.config` on Mids for Delivery Services which are LIVE and not NATL.

Fix TO to not add remap rules for Live DSs on mids

---

traffic_ops/app/lib/UI/ConfigFiles.pm

ATS has an issue where it cannot figure out what volume to assign
to a replacement drive if other drives already have an existing
volume assignment. Explicitly setting the volume parameter for every
drive in storage.config works around this issue.
This is a fix for issue #1253

Always insert a 'volume=x' parameter into storage.config

---

traffic_stats/grafana/traffic_ops_deliveryservice.js
traffic_stats/traffic_stats.go

Also updated the DS scripted dashboard to account for type data.

Updated Traffic Stats to handle DS Type data

---

traffic_ops/app/lib/UI/Server.pm

I checked the other ip6 fields and ip6_address only seems to be the one causing problems.
this closes #1303

don't add ip6_address as empty string

---

traffic_ops/app/lib/UI/Server.pm

(cherry picked from commit 4358877fb21a293e1fc10352790eb522bcc515ef)

BACKPORT - don't add ip6_address as empty string

---

traffic_ops/experimental/url-rewriter-nginx/Url_Rewriter_Dockerfile

This Dockerfile creates a Docker image with NGINX configured to
rewrite requests of a format we want, to that expected by PostgREST.

Add TO2.0 API Url Rewriter Dockerfile

---

traffic_ops/app/lib/UI/ConfigFiles.pm

Changes Traffic Ops to calculate volume numbers from *Drive_Prefix
parameters, instead of using separate Volume parameters.
Resolves #1334

Add Traffic Ops logic to calculate volumes

---

traffic_ops/app/lib/API/Server.pm
traffic_ops/app/t/api/1.2/server.t

If a client passes in an empty string for ip6_address, just ignore it.

don't allow an empty string to be passed in as ip6_address in the API

---

traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/CacheWatcher.java

Traffic Monitor always clears list of updaters after fetching all stats

---

traffic_ops/install/bin/postinstall

Fixes postinstall to print a useful error when checking if default
profiles exist fails.
Fixes postinstall to print an informative message when profile
defaults aren't created because the $reconfigure_defaults file
exists.
Fixes #1359

Fix TO postinstall profile check error message

---

traffic_stats/build/traffic_stats.spec

Download the 0.11.1 version of influxdb client

---

traffic_ops/app/lib/UI/Cdn.pm
traffic_ops/app/lib/UI/Topology.pm

(cherry picked from commit ebbdb9e85e210df92707d5b1e5426faaae2b20a6)

Fix TO Diff CRConfig to check Geolimit Countrycode

---

traffic_monitor/src/main/bin/traffic_monitor_config.pl

Fixes Docker, which doesn't set the `domainname`.
We could change Docker to not use `config.pl`, but, since the script was never actually using `domain_name`, removing the variable was the easiest fix.

Remove TM config.pl unused domainname call

---

traffic_ops/app/lib/TrafficOpsRoutes.pm

I added back in the original endpoint in addition to the changed one. This should now allow you to send a request ending in .json or not. 
I would like to understand the original issue this was trying to fix with spaces not being allowed in profile names, I did some curl for a profile with a space in the name and as long as you escape the profile name (with %20) it works....

Fix issue where /api/1.2/parameter/profile requests were failing if .json was on the URL

---

traffic_ops/app/lib/API/Parameter.pm

This is needed by Docker, to get the ID to update an existing param.

Add TO /parameters/profile ID value

---

traffic_ops/app/lib/UI/DeliveryService.pm

Fix bug #1431 
When Delivery Service is deleted,  delete all the config parameters which belong to it.

TO: Delete config file parameters when deleting Delivery Service

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessEventBuilder.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/DNSAccessEventBuilderTest.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/dns/protocol/AbstractProtocolTest.java

A TTL will be logged for each IP in the answer.  The TTL field was also moved to right before the answer. The answer will now look something like this:  
`1465230613.478 qtype=DNS chi=10.1.1.1 ttms=13 xn=44901 fqdn=edge.ds-01.mycdn.kabletown.net. type=A class=IN rcode=NOERROR rtype=CZ rloc="0,0" rdtl=- rerr="-" ttl="30 30" ans="192.168.1.2 192.168.1.1"`
This fixes #1489

Traffic Router now logs TTLs in the access log

---

traffic_ops/install/bin/postinstall

postinstall gives a warning 'my $ans' masked by earlier declaration (paraphrased) at line 701.   Adds code blocks to limit the scope of the declaration.

add enclosing block to avoid var masking warning

---

traffic_ops/bin/traffic_ops_ort.pl

This pull request contains changes to traffic_ops_ort.pl following integration testing on a CentOS 7 machine.  Changes are principally around the system V init script commands service and chkconfig and the systemd commands used in centos 7.  These changes were made to fix centos 7 integration issues.  I think that the traffic ops chkconfig endpoint needs to be generalized to support both chkconfig and systemd.  Following this, these changes should be refactored to better abstract systemd and chkconfig differences.
NOTE:  Centos 6 regression testing is in progress.  I'll update this PR with regression test results.

Centos7 ort integration.

---

traffic_router/core/src/main/conf/log4j.properties

Traffic Router now logs at the INFO level for any packages and classes under the  com.comcast.cdn.traffic_control.traffic_router package.  Since we are logging info for all classes under the traffic_router package we no longer need the individual package config.
This fixes #1498

Traffic Router now logs INFO for all modules

---

traffic_ops/install/bin/generateCert
traffic_ops/install/bin/postinstall

Fixes #1386 
this guarantees not in separate file system, so no cross-device link error.
To test: `export TMPDIR=<directory in another file system>` and run previous version and then this one.   May need to touch /opt/traffic_ops/.reconfigure to force conf file to be re-created.

create tmp file in same dir as conf

---

traffic_monitor/src/main/java/com/comcast/cdn/traffic_control/traffic_monitor/health/AbstractState.java

If a server is set from REPORTED to OFFLINE (or deleted) and then CrConfig is snapshotted, the server is no longer in CrConfig or CrStates.  When this happens, peer states shows a value of "" for the server.  Instead of showing "" for the server, Traffic Monitor will now show "false".
This addresses #1535

If TM doesn't get a valid DataPoint value from peer then default to false instead of empty string

---

traffic_monitor/pom.xml
traffic_router/build/pom.xml

git short hash now has 8 characters instead of 9 in rpm names for TM and TR

---

traffic_stats/grafana/traffic_ops_server.js

If you have telegraf data for a server (specifically cpu, mem, system, and diskio) you will now get some new graphs when you click on the server graph.  If you do not have telegraf data for the cache then you will get empty graphs.  
Also fixed an issue where connections were getting multiplied by 1000.
The new graphs that show are CPU usage, Memory Usage, Load Average, and Read/Write time.

Updated server scripted dashboard to include telegraf data

---

traffic_ops/app/templates/ssl_keys/add.html.ep

The text for generating new keys is "Generate Keys", the text for pasting existing keys is "Load Keys".
This fixes #876

Submit button for SSL Keys now shows correct text

---

traffic_ops/build/traffic_ops.spec

install of YAML module requires Test::More,  which is in perl-core module.   That needs to be installed for a clean install from scratch.  Now installed by yum/rpm as dependency for traffic_ops

add perl-core to dependencies to get Test::More

---

traffic_ops/bin/traffic_ops_ort.pl

Simple change to set the start_service message to only show up during debugging rather than error-level feedback.

change start_service to DEBUG level message

---

traffic_ops/app/lib/TrafficOpsRoutes.pm

This is due to the way Mojolicious parses placeholders. The standard placeholders match on the period which causes the placeholder's value to be truncated at the period. Using the relaxed method is less greedy and allows one to use periods in a placeholder.

Modified two routes to use relaxed placeholders to fix issue #1598.

---

traffic_stats/grafana/traffic_ops_server.js

This fixes an issue found in 1.6.0 where telegraf data was not showing up on the server scripted dashboard because the query needed to use a regex.

Change telegraf queries to use regex so they work

---

traffic_ops/app/lib/API/Cdn.pm

Ops now correctly sends cert from endpoint /api/1.2/cdns/name/<cdnname>/sslkeys.json

---

build/functions.sh
traffic_ops/build/build_rpm.sh
traffic_stats/build/build_rpm.sh

traffic_monitor, traffic_router, traffic_portal don't require go:  not required when only one of these is being built

move go requirement down into subsystems requiring it

---

traffic_portal/build/README.md
traffic_portal/build/build_rpm.sh

no longer can you pass in build_no and version - also, renamed $branch to $version and also adds sha to rpm name.
related to issue #1636

traffic portal rpm cleanup

---

traffic_ops/app/bin/db/setup_kabletown.pl

small change -- don't set MOJO_MODE if already set in environment.

allows override of MOJO_MODE for kabletown sample data

---

traffic_ops/app/lib/UI/Cdn.pm

The DataTables java script library expects to get back an array at app/public/js/jquery.dataTables.js line 3284
We were sending back null which was blowing up javascript as evidenced in the javascript console in my browser

TO now displays 'no data available in table' instead of hanging with message 'processing...'

---

traffic_ops/app/lib/API/DeliveryService.pm
traffic_ops/app/lib/MojoPlugins/DeliveryService.pm
traffic_ops/app/lib/UI/ConfigFiles.pm
traffic_ops/app/lib/UI/DeliveryService.pm
traffic_ops/app/t/api/1.2/deliveryservice.t

Used to get a bogus error that I was trying to add a host regex that was already taken by another delivery service. However the other delivery service was not in the same cdn.

TO now allows editing delivery services in different cdn's with the same host regex

---

traffic_stats/traffic_stats.go

Traffic Stats now uses continuous queries to calculate daily stats.  This is to address an issue where daily stats, specifically daily_bytesserved, was not correctly calculated once our CDN got to be > 1000 caches.  
This fixes #1669

Traffic Stats now correctly calculates daily stats

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/AbstractServiceUpdater.java

When there is no delivery service which use RGB function,  the downloading of RGB file should be stopped.

#1730: Stop RGB File downloading when RGB func not use

---

traffic_ops/app/lib/Extensions/TrafficStats/API/CacheStats.pm
traffic_stats/influxdb_tools/create_ts_databases.go

Updated create_ts_databases.go to create two new continuous queries for maxkbps which is used to determine maxGbps available on the CDN.  The new continuous queries need to be run in order for the calculation to work.  Can be run manually or by running traffic_stats/influxdb_tools/create_ts_databases.
This fixes #1681

Fix available percentage on traffic ops Health -> Graph View page

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/hash/ConsistentHasher.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/hashing/ConsistentHasherTest.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouterTest.java

Traffic Router now correctly performs consistent hashing or dispersion. 
This fixes #1767 in master, will need to be cherry picked to 1.6.0.

Fix consistent hashing in Traffic Router

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/hash/ConsistentHasher.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouter.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/hashing/ConsistentHasherTest.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/router/TrafficRouterTest.java

Traffic Router now correctly performs consistent hashing or dispersion.
This fixes #1767.

CHERRY PICK: Fix consistent hashing in Traffic Router

---

traffic_ops/app/lib/UI/ConfigFiles.pm
traffic_ops/app/lib/UI/DeliveryService.pm

I searched for 'protocol' on the project and these seemed to be the obvious items left out that depend on adding the http to https option for delivery service 'protocol'

Update dependencies upon delivery service protocol 'http to https'

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/ds/SteeringRegistry.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/ds/SteeringWatcher.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/AbstractServiceUpdater.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/FederationsWatcher.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/MaxmindGeolocationService.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/NetworkNode.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/NetworkUpdater.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/RegionalGeo.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/RegionalGeoUpdater.java
traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/util/AbstractResourceWatcher.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/NetworkNodeTest.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/NetworkNodeUnitTest.java
traffic_router/core/src/test/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/RegionalGeoTest.java

@dneuman64 @trevorackerman Please help to review this revised version, thanks.
To fix TR download invalid db issue #1449. And this is a revised version for the old PR #1541.
This time, I am implementing the verifyDatabase() for all subclasses of AbstractServiceUpdater. If it fails, do not copy the downloaded DB.
I have tested it on NetworkUpdater, RegionalGeo, and GeolocationDatabase, but not on SteeringWatcher and FederationsWatcher.

Fix TR download invalid db issue -- version2

---

traffic_ops/app/lib/UI/Server.pm

The issue was that the UI was not receiving a response from the controller so the UI kept submitting the request over and over again.  Adding a re-direct solves this issue.
This fixes #1570

Traffic Ops no longer submits queue update requests over and over

---

traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/hash/MD5HashFunction.java

Was observing array index out of bounds exceptions in qa testing.
This fixes it.

Sharing message digest object is not thread safe

---

traffic_monitor/experimental/traffic_monitor/cache/cache.go
traffic_monitor/experimental/traffic_monitor/deliveryservice/stat.go
traffic_monitor/experimental/traffic_monitor/health/cache_health.go
traffic_monitor/experimental/traffic_monitor/manager/datarequest.go
traffic_monitor/experimental/traffic_monitor/manager/events.go
traffic_monitor/experimental/traffic_monitor/manager/healthresult.go
traffic_monitor/experimental/traffic_monitor/manager/monitorconfig.go
traffic_monitor/experimental/traffic_monitor/manager/peer.go
traffic_monitor/experimental/traffic_monitor/peer/crstates.go
traffic_monitor/experimental/traffic_monitor/peer/peer.go
traffic_monitor/experimental/traffic_monitor/trafficopsdata/trafficopsdata.go

Changes strings which refer to names to be the proper type, e.g.
CacheName, DeliveryServiceName. (This aids readability, knowing what
a string is; its biggest benefit is in maps, e.g. `map[CacheName]int`
instead of `map[string]int`.)
Fixes #1853

Change TM2 name strings to types

---

traffic_router/keystore/src/main/java/com/comcast/cdn/traffic_control/traffic_router/keystore/KeyManager.java

This fixes #1880
(cherry picked from commit 08df3028e7cfcf0ea69c318be395af26d53693d8)

TR no longer reverses the order of the certificate chain.  

---

traffic_monitor/experimental/traffic_monitor/cache/cache.go
traffic_monitor/experimental/traffic_monitor/http_server/http_server.go
traffic_monitor/experimental/traffic_monitor/index.html
traffic_monitor/experimental/traffic_monitor/manager/datarequest.go

Fixes TM2 bandwidth capacity to expect mbps from ATS and return kbps.
Adds commas to the GUI bandwidth numbers.

Fix Traffic Monitor 2.0 Bandwidth Capacity, Add GUI Bandwidth Commas

---

traffic_monitor/experimental/traffic_monitor/trafficopswrapper/trafficopswrapper.go
traffic_ops/client/crconfig.go
traffic_ops/client/traffic_ops.go
traffic_ops/client/traffic_router_config.go

Changes the Traffic Ops Client to not log, and to return all formerly
logged information so users can decide whether to log, and in their
own format.
Fixes #1925

Change TO client to not log

---

traffic_stats/build/build_rpm.sh
traffic_stats/build/traffic_stats.spec
traffic_stats/influxdb_tools/sync_ts_databases.go
traffic_stats/traffic_stats.cfg
traffic_stats/traffic_stats.go

Traffic Stats now uses its config file to determine which influxdb urls to use.  This allows a user to run a single instance of influxdb, an enterprise clustered solution, or a HA solution using influxdb-relay (https://github.com/influxdata/influxdb-relay).  
This version of Traffic Stats requires Influxdb version 1.0.0 or greater.
This fixes #1668

Traffic Stats now uses its config file for InfluxDb Connections

---

traffic_monitor/experimental/traffic_monitor/cache/cache.go
traffic_monitor/experimental/traffic_monitor/deliveryservice/stat.go
traffic_monitor/experimental/traffic_monitor/deliveryservicedata/stat.go
traffic_monitor/experimental/traffic_monitor/index.html

This required completely rewriting the DS KBPS logic, to track per-cache bytes, and compute kbps for each cache, then sum them. Because otherwise, if a cache doesn't respond, it may be in a previous total DS bytes, but not the new one, resulting in wrong (and even negative) kbps.

Fix Traffic Monitor 2.0 DeliveryService Kbps

---

traffic_stats/traffic_stats.go

fixed #1825 
We found the tcp connections leak in traffic_stats 1.6.0. And verified the solution in 1.6.0.
The root cause is go "net/http" Client will keep idle connections for reuse. If we leave the influxDB client w/o explicitly close the transport, go GC could not re-collect the resources.
Please refer to https://github.com/influxdata/influxdb/pull/6425
Not sure why the recent code in master discard the original logic to re-use influxDB client like traffic_stats 1.6.0. But anyway, we need to close old client explicitly. Otherwise, there will be lots of tcp connections leak quickly.

close old connections explicitly to prevent tcp conn leak

---

traffic_monitor/experimental/traffic_monitor/manager/datarequest.go
traffic_monitor/experimental/traffic_monitor/manager/healthresult.go
traffic_monitor/experimental/traffic_monitor/manager/manager.go
traffic_monitor/experimental/traffic_monitor/manager/monitorconfig.go
traffic_monitor/experimental/traffic_monitor/manager/peer.go
traffic_monitor/experimental/traffic_monitor/manager/stathistory.go

Changes function definitions and calls to put each param on its own
line. These managers have a large number of parameters. This makes it
easier to read, and makes diffs better.
Fixes #2012

Change TM2 manager params to be multiline

---

traffic_monitor/experimental/traffic_monitor/manager/datarequest.go
traffic_monitor/experimental/traffic_monitor/manager/manager.go
traffic_monitor/experimental/traffic_monitor/manager/monitorconfig.go
traffic_monitor/experimental/traffic_monitor/manager/opsconfig.go
traffic_monitor/experimental/traffic_monitor/manager/polledcaches.go
traffic_monitor/experimental/traffic_monitor/manager/stathistory.go

Fixes Traffic Monitor 2.0 to return 503 Service Unavailable to all
requests, until all caches have either been polled twice and have
a bandwidth set, or have failed to respond properly.
This is necessary, because otherwise, interdependent components such
as Traffic Router could request and get a partial result, with wrong
availability, bandwidth, and other numbers.
Fixes #2017

Fix TM2 to return 503 until all caches are polled

---

traffic_ops/app/cpanfile

new won't install with perl 5.10

Google::ProtocolBuffers to previous version
